#!/usr/bin/env python3
"""Bundle source modules and package an offline-ready static site; no npm dependencies."""
from pathlib import Path
import argparse
import hashlib
import re
import shutil
import zipfile

HERE = Path(__file__).resolve().parent
PAGES = ('index.html', 'lod.html', 'wireframe.html', 'pointcloud.html')
ICONS = ('favicon.svg', 'favicon.ico', 'favicon-32.png', 'apple-touch-icon.png')
ENTRIES = {'hub': 'src/hub/hub.js', 'lod': 'src/lod/app.js', 'cloud': 'src/cloud/cloud-app.js'}
IMPORT = re.compile(r"^import\s+\{[^}]+\}\s+from\s+['\"]([^'\"]+)['\"];?\s*$", re.MULTILINE)


def bundle(entry):
    pieces, visited, active = [], set(), set()
    def visit(path):
        path = path.resolve()
        if HERE / 'src' not in path.parents:
            raise ValueError(f'Import outside src/: {path}')
        if path in active:
            raise ValueError(f'Circular import: {path}')
        if path in visited:
            return
        active.add(path)
        source = path.read_text(encoding='utf-8')
        for match in IMPORT.finditer(source):
            if not match[1].startswith('.'):
                raise ValueError(f'Only relative imports are supported: {match[1]}')
            visit(path.parent / match[1])
        source = IMPORT.sub('', source)
        source = re.sub(r'^export\s+(?=(?:async\s+)?(?:function|class|const|let|var)\b)', '', source, flags=re.MULTILINE)
        if re.search(r'^\s*(?:import|export)\b', source, flags=re.MULTILINE):
            raise ValueError(f'Unsupported module syntax: {path}')
        pieces.append(f'\n// Source: {path.relative_to(HERE)}\n{source}')
        active.remove(path); visited.add(path)
    visit(HERE / entry)
    return "// Generated by build.py. Edit src/, not this file.\n(() => {\n'use strict';\n" + '\n'.join(pieces) + '\n})();\n'


def site_files():
    return [*PAGES, *ICONS, *[str(p.relative_to(HERE)) for p in sorted((HERE / 'assets').rglob('*')) if p.is_file()]]


def boot_page(source):
    """Generate critical startup UI from one shared source for all four entry pages."""
    head = '<style>' + (HERE / 'src/shared/page-boot.css').read_text(encoding='utf-8') + '</style>\n<script>' + (HERE / 'src/shared/page-boot.js').read_text(encoding='utf-8') + '</script>'
    body = (HERE / 'src/shared/page-boot.html').read_text(encoding='utf-8')
    for name, content in [('head',head), ('body',body)]:
        pattern = r'<!-- boot-' + name + r':start -->[\s\S]*?<!-- boot-' + name + r':end -->'
        source = re.sub(pattern, lambda _: '<!-- boot-' + name + ':start -->\n' + content + '\n<!-- boot-' + name + ':end -->', source)
    return source


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument('--site', action='store_true')
    cli.add_argument('--zip', action='store_true')
    cli.add_argument('--check', action='store_true', help='Fail if tracked bundles are stale; do not write')
    args = cli.parse_args()
    for name, entry in ENTRIES.items():
        target = HERE / 'assets' / 'js' / f'{name}.bundle.js'
        output = bundle(entry)
        if args.check:
            if not target.exists() or target.read_text(encoding='utf-8') != output:
                raise SystemExit(f'Stale bundle: {target.relative_to(HERE)}; run python3 build.py')
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(output, encoding='utf-8')
        print(f'{"Checked" if args.check else "Built"} {target.relative_to(HERE)}')
    for name in PAGES:
        path = HERE / name
        source = path.read_text(encoding='utf-8')
        output = boot_page(source)
        def asset_version(match):
            name = match[2]
            digest = hashlib.sha256((HERE / name).read_bytes()).hexdigest()[:12]
            return match[1] + name + '?v=' + digest + match[3]
        output = re.sub(r'(\b(?:src|href)=[\"\'])(assets/[^\"\'?]+)(?:\?[^\"\']*)?([\"\'])', asset_version, output)
        if args.check:
            if source != output: raise SystemExit(f'Stale startup shell: {name}; run python3 build.py')
        else: path.write_text(output, encoding='utf-8')
    if args.site:
        target = HERE / '_site'
        if target.is_symlink():
            raise ValueError('Refusing to replace a symlink at _site')
        if target.exists(): shutil.rmtree(target)
        target.mkdir()
        for name in site_files():
            (target / name).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(HERE / name, target / name)
        (target / '.nojekyll').touch()
        print(f'Static website: {target}')
    if args.zip:
        files = site_files() + ['build.py','server.py','start.sh','package.json','README.md','README.en.md','.gitignore','.gitattributes']
        for folder in ['src','tests','scripts','docs','.github']:
            files.extend(str(f.relative_to(HERE)) for f in sorted((HERE / folder).rglob('*')) if f.is_file())
        target = HERE / 'dist' / 'BuildingWebViewer.zip'
        target.parent.mkdir(exist_ok=True)
        with zipfile.ZipFile(target,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as archive:
            for name in sorted(set(files)): archive.write(HERE / name, 'BuildingWebViewer/' + name)
        print(f'Package: {target} ({target.stat().st_size:,} bytes; no datasets)')


if __name__ == '__main__': main()
