#!/usr/bin/env python3
"""Build BuildingWebViewer scripts, a static website, and a data-free project ZIP."""
from pathlib import Path
import argparse
import re
import shutil
import zipfile

HERE = Path(__file__).resolve().parent
SITE_FILES = [
    'index.html', 'hub.css', 'lod.html', 'wireframe.html', 'pointcloud.html',
    'styles.css', 'cloud.css', 'viewer.js', 'cloud-app.bundle.js',
]
FILES = SITE_FILES + [
    'renderer.js', 'obj-parser.js', 'app.js',
    'cloud-app.js', 'cloud-renderer.js', 'point-io.js',
    'server.py', 'start.sh', 'build.py', 'README.md', 'point-io.test.mjs', 'cloud-renderer.test.mjs',
    '.gitignore', '.gitattributes', '.github/workflows/pages.yml',
]
BUNDLES = {
    'viewer.js': ['renderer.js', 'obj-parser.js', 'app.js'],
    'cloud-app.bundle.js': ['cloud-renderer.js', 'point-io.js', 'cloud-app.js'],
}


def bundle(output, filenames):
    pieces = []
    for name in filenames:
        source = (HERE / name).read_text(encoding='utf-8')
        # Sources use named exports/imports only; reject anything this tiny
        # bundler cannot faithfully compose instead of silently shipping it.
        def remove_import(match):
            imported = match.group(1)
            if not imported.startswith('./') or imported[2:] not in filenames:
                raise ValueError(f'{name}: unsupported module import {imported!r}')
            return ''
        source = re.sub(r"^import\s+\{[^}]+\}\s+from\s+['\"]([^'\"]+)['\"];?\s*$",
                        remove_import, source, flags=re.MULTILINE)
        source = re.sub(r'^export\s+(?=(?:async\s+)?(?:function|class|const|let|var)\b)',
                        '', source, flags=re.MULTILINE)
        if re.search(r'^\s*(?:import|export)\b', source, flags=re.MULTILINE):
            raise ValueError(f'{name}: unsupported import/export syntax')
        pieces.append(f'\n// Source: {name}\n{source}')
    header = "// Generated by build.py; edit source files and rebuild.\n(() => {\n'use strict';\n"
    (HERE / output).write_text(header + '\n'.join(pieces) + '\n})();\n', encoding='utf-8')


def build():
    for output, filenames in BUNDLES.items():
        bundle(output, filenames)
        print(f'Built {HERE / output}')


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument('--site', action='store_true', help='Create _site/ with only browser assets for static hosting')
    cli.add_argument('--zip', action='store_true', help='Create dist/BuildingWebViewer.zip; no models or Git history')
    args = cli.parse_args()
    build()
    if args.site:
        target = HERE / '_site'
        if target.is_symlink():
            raise ValueError('Refusing to replace a symlink at _site')
        if target.exists():
            shutil.rmtree(target)
        target.mkdir()
        for name in SITE_FILES:
            shutil.copy2(HERE / name, target / name)
        (target / '.nojekyll').touch()
        print(f'Static website: {target} ({len(SITE_FILES)} browser assets; no model data)')
    if args.zip:
        missing = [name for name in FILES if not (HERE / name).is_file()]
        if missing:
            raise FileNotFoundError('Missing package assets: ' + ', '.join(missing))
        target = HERE / 'dist' / 'BuildingWebViewer.zip'
        target.parent.mkdir(exist_ok=True)
        with zipfile.ZipFile(target, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
            for name in FILES:
                archive.write(HERE / name, 'BuildingWebViewer/' + name)
        print(f'Packaged {target} ({target.stat().st_size:,} bytes; no model data)')


if __name__ == '__main__':
    main()
