import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PointProject} = await import(`data:text/javascript;base64,${Buffer.from(await readFile(new URL('./point-project.js', import.meta.url))).toString('base64')}`);
const project = new PointProject(), entries = [{id:'data/a.txt',key:'a'}, {id:'data/sub/b.txt',key:'b'}, {id:'other/c.txt',key:'c'}];
entries.forEach(entry => project.assign(entry,entry.id));
assert.equal(project.groups.size,3); assert.equal(project.path(entries[1].group),'data/sub');
assert.equal(entries[1].treeName,'b.txt');
console.log('PASS folder imports preserve root and nested hierarchy');
const root = entries[0].group, sub = entries[1].group;
assert.equal(project.members(root,entries).length,2);
project.groups.get(sub).collapsed=true;
assert.equal(project.members(root,entries).length,2);
assert(project.matches(entries[1],'data/sub')); assert(project.matches(entries[1],'B.TXT'));
console.log('PASS recursive group selection and search include collapsed descendants');
const group = project.create('Review'); project.move(entries[0],group);
assert.equal(project.path(entries[0].group),'Review'); assert.equal(entries[0].id,'data/a.txt'); assert.equal(entries[0].key,'a');
project.move(entries[0],''); assert.equal(entries[0].group,'');
console.log('PASS cloud moves preserve source identity and can return to project root');
assert.throws(()=>project.move(root,sub),/自身/); assert.throws(()=>project.move(root,root),/自身/);
assert.equal(project.groups.get(root).parent,'');
project.move(sub,group); assert.equal(project.path(sub),'Review/sub');
assert(project.matches(entries[1],'Review'));
console.log('PASS group moves update descendant paths and reject cycles');
assert.throws(()=>project.create('Review'),/同名/); assert.throws(()=>project.create('../bad'),/斜线/);
assert.throws(()=>project.create(''),/名称/); assert.throws(()=>project.move(entries[0],'missing'),/不存在/);
const duplicate = project.create('sub'); assert.throws(()=>project.move(sub,''),/同名/);
assert.equal(project.groups.get(sub).parent,group);
console.log('PASS invalid names, stale destinations and sibling conflicts leave groups intact');
const removing=project.members(group,entries); assert.deepEqual(removing,[entries[1]]);
project.removeGroup(group); assert(!project.groups.has(group)); assert(!project.groups.has(sub));
assert(project.groups.has(duplicate)); assert(project.groups.has(root));
console.log('PASS recursive removal identifies only contained clouds and folders');
