import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PointProject} = await import(`data:text/javascript;base64,${Buffer.from(await readFile(new URL('./point-project.js', import.meta.url))).toString('base64')}`);
const project = new PointProject(), entries = [{id:'data/a.txt',key:'a'}, {id:'data/sub/b.txt',key:'b'}, {id:'other/c.txt',key:'c'}];
entries.forEach(entry => project.assign(entry,entry.id));
assert.equal(project.groups.size,3); assert.equal(project.path(entries[1].group),'data/sub');
assert.equal(entries[1].treeName,'b.txt');
console.log('PASS folder imports preserve root and nested hierarchy');
const root = entries[0].group, sub = entries[1].group;
assert.equal(project.members(root,entries).length,2);
project.groups.get(sub).collapsed=true;
assert.equal(project.members(root,entries).length,2);
assert(project.matches(entries[1],'data/sub')); assert(project.matches(entries[1],'B.TXT'));
console.log('PASS recursive group selection and search include collapsed descendants');
const group = project.create('Review'); project.move(entries[0],group);
assert.equal(project.path(entries[0].group),'Review'); assert.equal(entries[0].id,'data/a.txt'); assert.equal(entries[0].key,'a');
project.move(entries[0],''); assert.equal(entries[0].group,'');
console.log('PASS cloud moves preserve source identity and can return to project root');
assert.throws(()=>project.move(root,sub),/自身/); assert.throws(()=>project.move(root,root),/自身/);
assert.equal(project.groups.get(root).parent,'');
project.move(sub,group); assert.equal(project.path(sub),'Review/sub');
assert(project.matches(entries[1],'Review'));
console.log('PASS group moves update descendant paths and reject cycles');
assert.throws(()=>project.create('Review'),/同名/); assert.throws(()=>project.create('../bad'),/斜线/);
assert.throws(()=>project.create(''),/名称/); assert.throws(()=>project.move(entries[0],'missing'),/不存在/);
const duplicate = project.create('sub'); assert.throws(()=>project.move(sub,''),/同名/);
assert.equal(project.groups.get(sub).parent,group);
console.log('PASS invalid names, stale destinations and sibling conflicts leave groups intact');
const removing=project.members(group,entries); assert.deepEqual(removing,[entries[1]]);
project.removeGroup(group); assert(!project.groups.has(group)); assert(!project.groups.has(sub));
assert(project.groups.has(duplicate)); assert(project.groups.has(root));
console.log('PASS recursive removal identifies only contained clouds and folders');

const {PointManagementSelection,pointBoxIntersects,projectSidebarWidth} = await import(`data:text/javascript;base64,${Buffer.from(await readFile(new URL('./point-project.js', import.meta.url))).toString('base64')}`);
const selection = new PointManagementSelection(), [a,b,c] = entries;
selection.select(a); selection.select(c,{toggle:true}); assert.deepEqual([...selection.items],[a,c]);
selection.select(a,{toggle:true}); assert.deepEqual([...selection.items],[c]);
selection.select(a); selection.select(c,{range:true,ordered:[a,b,c]}); assert.deepEqual([...selection.items],[a,b,c]);
selection.select(b); assert.deepEqual([...selection.items],[b]);
console.log('PASS Ctrl toggles independent management selection; Shift selects a visible range');
selection.box([a,c],[b]); assert.deepEqual([...selection.items],[b,a,c]);
selection.box([a]); assert.deepEqual([...selection.items],[a]); selection.clear(); assert.equal(selection.anchor,null);
assert(pointBoxIntersects({left:0,right:50,top:0,bottom:20},{left:10,right:30,top:10,bottom:30}));
assert(!pointBoxIntersects({left:0,right:50,top:0,bottom:20},{left:10,right:30,top:20,bottom:30}));
console.log('PASS rectangle selection can replace or add without changing cloud visibility');
const batch = new PointProject(), clouds = [{id:'folder/a.txt'},{id:'folder/sub/b.txt'},{id:'other/c.txt'}];
clouds.forEach(entry=>batch.assign(entry,entry.id));
const folder=clouds[0].group, nestedGroup=clouds[1].group, target=batch.create('Target');
assert.deepEqual(batch.roots([folder,nestedGroup,clouds[0],clouds[1],clouds[2]]),[folder,clouds[2]]);
assert.equal(batch.files([folder,nestedGroup,clouds[0]],clouds).length,2);
batch.moveMany([folder,nestedGroup,clouds[0],clouds[2]],target);
assert.equal(batch.path(clouds[1].group),'Target/folder/sub'); assert.equal(clouds[2].group,target);
assert.equal(clouds[0].id,'folder/a.txt');
console.log('PASS multi-move treats selected parents and children once and preserves source identities');
const collisionParent=batch.create('Elsewhere'), collision=batch.create('folder',collisionParent);
const before=clouds[2].group;
assert.throws(()=>batch.moveMany([clouds[2],folder],collisionParent),/同名/);
assert.equal(clouds[2].group,before); assert.equal(batch.groups.get(folder).parent,target);
assert.throws(()=>batch.moveMany([clouds[2],folder],nestedGroup),/自身/);
assert.equal(clouds[2].group,before);
console.log('PASS conflicting/cyclic batch moves are atomic and never partially move point clouds');
const sameA=batch.create('same'), sameB=batch.create('same',collisionParent);
assert.throws(()=>batch.moveMany([sameA,sameB],target),/同名/);
assert.equal(batch.groups.get(sameA).parent,''); assert.equal(batch.groups.get(sameB).parent,collisionParent);
console.log('PASS same-name groups in one batch are rejected before any mutation');
assert.equal(projectSidebarWidth(100,1280),240);assert.equal(projectSidebarWidth(800,1280),500);
assert.equal(projectSidebarWidth(500,1200,true),492); assert.equal(projectSidebarWidth(NaN,1280),300);
console.log('PASS sidebar width keeps a usable viewport and restores the default size');
