// Generated by build.py; edit source files and rebuild.
(() => {
'use strict';

// Source: viewer-layout.js
/** A shared, non-modal inspector: the canvas remains usable while editing. */
function mountViewerLayout({root = document} = {}) {
  const panel = root.getElementById('viewer-inspector');
  if (!panel) return null;
  const workspace = panel.parentElement;
  const triggers = [...root.querySelectorAll('[data-open-settings]')];
  const tabs = [...panel.querySelectorAll('[data-settings-tab]')];
  const sections = [...panel.querySelectorAll('[data-settings-panel]')];
  const closeButton = panel.querySelector('[data-close-settings]');
  let current = 'display', returnFocus = null;

  function select(name, focus = false) {
    if (!tabs.some(tab => tab.dataset.settingsTab === name)) return;
    current = name;
    for (const tab of tabs) {
      const active = tab.dataset.settingsTab === name;
      tab.setAttribute('aria-selected', String(active)); tab.tabIndex = active ? 0 : -1;
      if (active && focus) tab.focus();
    }
    for (const section of sections) section.hidden = section.dataset.settingsPanel !== name;
    for (const trigger of triggers) {
      const active = !panel.hidden && trigger.dataset.openSettings === name;
      trigger.setAttribute('aria-expanded', String(active));
      trigger.classList.toggle('active', active);
    }
    // A second disclosure inside the display tab would hide the very controls
    // the user has just asked to open. Standalone palette panels remain unchanged.
    const palette = panel.querySelector('.palette-panel');
    if (palette) palette.open = true;
  }
  function close() {
    if (panel.hidden) return;
    const hadFocus = panel.contains(root.activeElement);
    panel.hidden = true; workspace.classList.remove('inspector-open'); select(current);
    if (hadFocus) returnFocus?.focus();
  }
  function open(name, trigger = null) {
    returnFocus = trigger || returnFocus;
    panel.hidden = false; workspace.classList.add('inspector-open'); select(name, true);
  }
  for (const trigger of triggers) trigger.addEventListener('click', () => {
    const name = trigger.dataset.openSettings;
    if (!panel.hidden && name === current) close(); else open(name, trigger);
  });
  for (const [index, tab] of tabs.entries()) {
    tab.addEventListener('click', () => select(tab.dataset.settingsTab));
    tab.addEventListener('keydown', event => {
      const target = event.key === 'ArrowRight' ? (index + 1) % tabs.length
        : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length
        : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : -1;
      if (target < 0) return;
      event.preventDefault(); select(tabs[target].dataset.settingsTab, true);
    });
  }
  closeButton.addEventListener('click', close);
  root.addEventListener('keydown', event => {
    if (event.key === 'Escape' && !event.defaultPrevented && !panel.hidden) { event.preventDefault(); close(); }
  });
  select(current);
  return {open, close};
}


// Source: palettes.js
/** Shared, evenly spaced color stops for GPU rendering and matching UI legends. */
const PALETTE_DEFINITIONS = Object.freeze({
  current: {label: '当前色带', stops: [[.20,.32,.65],[.13,.59,.70],[.35,.75,.55],[.90,.80,.32],[.88,.33,.23]]},
  viridis: {label: 'Viridis', stops: [[.267,.005,.329],[.279,.175,.483],[.230,.322,.546],[.173,.449,.558],[.128,.567,.551],[.158,.684,.502],[.369,.789,.383],[.678,.864,.190],[.993,.906,.144]]},
  inferno: {label: 'Inferno', stops: [[.001,.000,.014],[.129,.047,.291],[.342,.062,.429],[.541,.135,.415],[.735,.216,.330],[.894,.353,.194],[.978,.558,.035],[.974,.798,.206],[.988,.998,.645]]},
  grayscale: {label: '灰度', stops: [[.08,.08,.08],[.95,.95,.95]]},
  'blue-white-red': {label: '蓝—白—红', stops: [[.17,.35,.75],[.97,.97,.97],[.78,.16,.20]]},
});

function samplePalette(t, palette = 'current', reverse = false) {
  const stops = (PALETTE_DEFINITIONS[palette] || PALETTE_DEFINITIONS.current).stops;
  let value = Number.isFinite(t) ? Math.max(0, Math.min(1, t)) : .5;
  if (reverse) value = 1 - value;
  const at = value * (stops.length - 1), low = Math.min(stops.length - 2, Math.floor(at)), fraction = at - low;
  return stops[low].map((channel, i) => channel * (1 - fraction) + stops[low + 1][i] * fraction);
}

function paletteUniforms(palette = 'current', reverse = false) {
  const values = new Float32Array(27);
  for (let i = 0; i < 9; i++) values.set(samplePalette(i / 8, palette, reverse), i * 3);
  return values;
}

function validatePaletteOptions(options) {
  if (!Object.hasOwn(PALETTE_DEFINITIONS, options.palette || 'current')) throw new Error(`不支持的色带：${options.palette}`);
  if (options.range !== null && options.range !== undefined) {
    const {min, max} = options.range;
    if (!Number.isFinite(min) || !Number.isFinite(max) || min >= max) throw new Error('手动色域需要有限数值，且最小值必须小于最大值。');
  }
}

const PALETTE_GLSL = `
uniform vec3 colorStops[9];
vec3 paletteColor(float value) {
  float t = clamp(value, 0.0, 1.0) * 8.0;
  if (t <= 1.0) return mix(colorStops[0], colorStops[1], t);
  if (t <= 2.0) return mix(colorStops[1], colorStops[2], t - 1.0);
  if (t <= 3.0) return mix(colorStops[2], colorStops[3], t - 2.0);
  if (t <= 4.0) return mix(colorStops[3], colorStops[4], t - 3.0);
  if (t <= 5.0) return mix(colorStops[4], colorStops[5], t - 4.0);
  if (t <= 6.0) return mix(colorStops[5], colorStops[6], t - 5.0);
  if (t <= 7.0) return mix(colorStops[6], colorStops[7], t - 6.0);
  return mix(colorStops[7], colorStops[8], t - 7.0);
}`;


// Source: palette-controls.js

function paletteGradient(palette = 'current', reverse = false) {
  const stops = Array.from({length: 17}, (_, i) => `rgb(${samplePalette(i / 16, palette, reverse).map(v => Math.round(v * 255)).join(',')}) ${i / 16 * 100}%`);
  return `linear-gradient(to right,${stops.join(',')})`;
}

function mountPaletteControls({container, onChange = () => {}, getOptions = () => ({})}) {
  const initial = getOptions();
  const details = document.createElement('details'); details.className = 'palette-panel viewer-control-panel';
  details.innerHTML = `<summary><span>配色方案</span><i class="palette-preview" aria-hidden="true"></i><small class="palette-caption"></small></summary>
    <div class="palette-body"><label>色带<select aria-label="色带方案"><option value="current">蓝 → 绿 → 黄 → 红</option><option value="viridis">Viridis · 蓝紫 → 绿 → 黄</option><option value="inferno">Inferno · 黑紫 → 橙 → 黄</option><option value="grayscale">灰度 · 黑 → 白</option><option value="blue-white-red">蓝 → 白 → 红</option></select></label>
    <label class="check-label"><input class="palette-reverse" type="checkbox">反转色带</label>
    <label class="check-label"><input class="palette-auto" type="checkbox" checked>自动数值范围</label>
    <label>最小值<input class="palette-min" type="number" step="any" aria-label="色带最小值" disabled></label>
    <label>最大值<input class="palette-max" type="number" step="any" aria-label="色带最大值" disabled></label>
    <p class="palette-help">高度与数值属性使用色带；固定范围可让不同文件的相同数值对应相同颜色。</p><p class="palette-error" role="alert" hidden></p></div>`;
  container.append(details);
  const select = details.querySelector('select'), reverse = details.querySelector('.palette-reverse'), auto = details.querySelector('.palette-auto');
  const low = details.querySelector('.palette-min'), high = details.querySelector('.palette-max'), message = details.querySelector('.palette-error');
  let state = {palette: initial.palette || 'current', reverse: !!initial.reverse, range: initial.range || null}, enabled = true;
  select.value = state.palette; reverse.checked = state.reverse;
  if (state.range) { auto.checked = false; low.value = state.range.min; high.value = state.range.max; }
  const refresh = () => {
    details.querySelector('.palette-preview').style.background = paletteGradient(state.palette, state.reverse);
    details.querySelector('.palette-caption').textContent = enabled ? `${select.selectedOptions[0].textContent.split(' · ')[0]}${state.reverse ? ' · 反转' : ''}` : '选择高度或数值属性后启用';
    select.disabled = reverse.disabled = auto.disabled = !enabled;
    low.disabled = high.disabled = !enabled || auto.checked;
  };
  const change = () => {
    low.disabled = high.disabled = auto.checked || !enabled;
    if (!auto.checked && (low.value === '' || high.value === '' || !Number.isFinite(low.valueAsNumber) || !Number.isFinite(high.valueAsNumber) || low.valueAsNumber >= high.valueAsNumber)) {
      message.textContent = '请输入有效范围，最小值必须小于最大值。'; message.hidden = false; return;
    }
    message.hidden = true; state = {palette: select.value, reverse: reverse.checked, range: auto.checked ? null : {min: low.valueAsNumber, max: high.valueAsNumber}};
    refresh(); onChange({...state});
  };
  for (const input of [select, reverse, auto, low, high]) input.addEventListener('change', change);
  for (const input of [low, high]) input.addEventListener('input', change);
  refresh();
  return {getOptions: () => ({...state}), setScalarEnabled(value) {enabled = !!value; refresh();},
    setDataRange(range) {if (auto.checked && range && Number.isFinite(range.min) && Number.isFinite(range.max)) {
      low.value = range.min; high.value = range.max === range.min ? range.min + 1 : range.max;
    }}, destroy() {details.remove();}};
}


// Source: camera-controls.js
/** Shared orthographic camera snapshots and an optional, local-only control panel. */
const CAMERA_FORMAT = 'BuildingWebViewer.camera';
const CAMERA_BOOK_FORMAT = 'BuildingWebViewer.camera-bookmarks';
const CAMERA_SPACES = ['raw-world', 'lod-arrangement'];
const CAMERA_MAX_BOOKMARKS = 100;

function cameraObject(value) { return value && typeof value === 'object' && !Array.isArray(value); }
function cameraFinite(value, label) {
  if (typeof value !== 'number' || !Number.isFinite(value)) throw Error(`${label}必须是有限数值`);
  return value;
}
function cameraVector(value, length, label) {
  if (!Array.isArray(value) || value.length !== length) throw Error(`${label}需要 ${length} 个数值`);
  return value.map(number => cameraFinite(number, label));
}
function cameraSpace(space) {
  if (!CAMERA_SPACES.includes(space)) throw Error('相机坐标空间无效');
  return space;
}
function cameraScene(scene, space) {
  if (scene == null && space === 'raw-world') return null;
  if (!cameraObject(scene) || !Array.isArray(scene.ids) || scene.ids.length > 10000 || scene.ids.some(id => typeof id !== 'string' || id.length > 1024)) throw Error('相机场景需要有效的文件或楼栋 ID 列表');
  const result = {ids: [...scene.ids]};
  if (space === 'lod-arrangement') {
    if (!['real', 'normalized'].includes(scene.scale)) throw Error('LOD 相机需要记录实际比例或统一大小模式');
    result.scale = scene.scale;
  }
  return result;
}
function cameraSameScene(a, b) {
  return a?.scale === b?.scale && a?.ids?.length === b?.ids?.length && a.ids.every((id, index) => id === b.ids[index]);
}

/** Validate before mutating a viewer; snapshots use original-world or synthetic-layout targets. */
function validateCameraSnapshot(value, {space = value?.space, scene = null, checkScene = true} = {}) {
  cameraSpace(space);
  if (!cameraObject(value) || value.format !== CAMERA_FORMAT || value.version !== 1) throw Error('不是受支持的相机 JSON（需要 BuildingWebViewer.camera v1）');
  if (value.space !== space) throw Error('相机坐标空间不匹配：点云/线框视角与 LOD 排列视角不能直接互用');
  if (value.projection !== 'orthographic') throw Error('当前查看器仅支持正交相机');
  const source = value.camera;
  if (!cameraObject(source)) throw Error('相机参数缺失');
  const azimuth = cameraFinite(source.azimuth, '方位角'), elevation = cameraFinite(source.elevation, '仰角');
  const zoom = cameraFinite(source.zoom, '缩放倍率'), baseHeight = cameraFinite(source.baseHeight, '基准视野高度');
  const limits = space === 'lod-arrangement' ? {minElevation: 0, minZoom: .15, maxZoom: 30} : {minElevation: -89, minZoom: .02, maxZoom: 100};
  if (Math.abs(azimuth) > 1e6) throw Error('方位角数值过大');
  if (elevation < limits.minElevation || elevation > 90) throw Error(`仰角需在 ${limits.minElevation}° 至 90° 之间`);
  if (zoom < limits.minZoom || zoom > limits.maxZoom) throw Error(`缩放倍率需在 ${limits.minZoom} 至 ${limits.maxZoom} 之间`);
  if (!(baseHeight > 0) || !Number.isFinite(baseHeight / zoom)) throw Error('基准视野高度必须为有效正数');
  const savedScene = cameraScene(value.scene, space);
  if (space === 'lod-arrangement' && checkScene && !cameraSameScene(savedScene, cameraScene(scene, space))) throw Error(`LOD 布局不匹配：此书签需要楼栋 ${savedScene.ids.join(', ').slice(0, 160) || '（空）'}，比例模式为${savedScene.scale === 'real' ? '实际比例' : '统一展示大小'}。请先恢复该布局再加载。`);
  return {format: CAMERA_FORMAT, version: 1, space, projection: 'orthographic',
    camera: {azimuth: ((azimuth + 180) % 360 + 360) % 360 - 180, elevation, zoom,
      pan: cameraVector(source.pan, 2, '平移'), target: cameraVector(source.target, 3, '目标点'), baseHeight}, scene: savedScene};
}

function captureCameraSnapshot(viewer, {space, scene = null} = {}) {
  cameraSpace(space);
  if (!viewer?.camera) throw Error('相机尚未准备好');
  const origin = space === 'raw-world' ? cameraVector(viewer.origin || [0, 0, 0], 3, '原点') : [0, 0, 0];
  const target = cameraVector(viewer.target, 3, '目标点').map((value, axis) => value + origin[axis]);
  return validateCameraSnapshot({format: CAMERA_FORMAT, version: 1, space, projection: 'orthographic', scene,
    camera: {...viewer.camera, pan: [...viewer.camera.pan], target, baseHeight: viewer.baseHeight}}, {space, scene, checkScene: false});
}

function applyCameraSnapshot(viewers, snapshot, {space = snapshot?.space, scene = null, checkScene = true, pauseSync = callback => callback()} = {}) {
  const value = validateCameraSnapshot(snapshot, {space, scene, checkScene});
  if (!Array.isArray(viewers) || !viewers.length || viewers.some(viewer => !viewer?.camera || typeof viewer.render !== 'function')) throw Error('请先加载数据，再应用相机');
  // Validate every new local target first, so a bad panel cannot leave a partial update.
  const targets = viewers.map(viewer => {
    const origin = space === 'raw-world' ? cameraVector(viewer.origin || [0, 0, 0], 3, '原点') : [0, 0, 0];
    return value.camera.target.map((number, axis) => cameraFinite(number - origin[axis], '局部目标点'));
  });
  pauseSync(() => {
    viewers.forEach((viewer, index) => {
      viewer.camera = {azimuth: value.camera.azimuth, elevation: value.camera.elevation, zoom: value.camera.zoom, pan: [...value.camera.pan]};
      viewer.target = targets[index]; viewer.baseHeight = value.camera.baseHeight;
    });
    viewers.forEach(viewer => viewer.render());
  });
  return value;
}

function cameraBookmark(record, space, index) {
  if (!cameraObject(record) || typeof record.name !== 'string' || !record.name.trim() || record.name.length > 80) throw Error('书签名称需为 1–80 个字符');
  return {id: typeof record.id === 'string' && record.id.trim() && record.id.length <= 128 ? record.id : `import-${index}`,
    name: record.name.trim(), snapshot: validateCameraSnapshot(record.snapshot, {space, checkScene: false}),
    ...(typeof record.updatedAt === 'string' && record.updatedAt.length <= 64 && Number.isFinite(Date.parse(record.updatedAt)) ? {updatedAt: record.updatedAt} : {})};
}

function parseCameraBookmarks(input, space) {
  cameraSpace(space);
  const value = typeof input === 'string' ? JSON.parse(input) : input;
  if (value?.format === CAMERA_FORMAT) return {preserveView: true, bookmarks: [{id: 'import-0', name: '导入视角', snapshot: validateCameraSnapshot(value, {space, checkScene: false})}]};
  if (!cameraObject(value) || value.format !== CAMERA_BOOK_FORMAT || value.version !== 1 || value.space !== space || !Array.isArray(value.bookmarks) || value.bookmarks.length > CAMERA_MAX_BOOKMARKS) throw Error('书签 JSON 格式或坐标空间无效（最多 100 个书签）');
  const bookmarks = value.bookmarks.map((record, index) => cameraBookmark(record, space, index));
  if (new Set(bookmarks.map(record => record.id)).size !== bookmarks.length) throw Error('书签 ID 重复');
  return {preserveView: value.preserveView !== false, bookmarks};
}

function serializeCameraBookmarks(bookmarks, space, preserveView = true) {
  const value = {format: CAMERA_BOOK_FORMAT, version: 1, space: cameraSpace(space), preserveView: Boolean(preserveView), bookmarks};
  parseCameraBookmarks(value, space);
  return JSON.stringify(value, null, 2);
}

/**
 * Returns {preserveView, capture, restore, refresh, destroy}.
 * Pass a separate bookmarkContainer to mount camera and bookmarks in two tabs.
 * restore(saved, {checkScene:false}) preserves a view after changing data;
 * bookmark loads retain strict LOD scene checking.
 */
function mountCameraControls({container, bookmarkContainer = null, getViewers, space, getScene = () => null, pauseSync = callback => callback()} = {}) {
  cameraSpace(space);
  if (!container || typeof getViewers !== 'function') throw Error('相机面板需要挂载容器和 getViewers');
  const doc = container.ownerDocument, win = doc.defaultView || globalThis;
  const separateBookmarks = bookmarkContainer && bookmarkContainer !== container;
  const key = `BuildingWebViewer.camera-bookmarks.v1.${space}`;
  const limits = space === 'lod-arrangement' ? {minElevation: 0, minZoom: .15, maxZoom: 30} : {minElevation: -89, minZoom: .02, maxZoom: 100};
  const watches = new Map(), inputs = new Map(), sliders = new Map(), dragging = new Set();
  let bookmarks = [], preserveView = true, selectedBookmark = '', disposed = false, frame = null, idCounter = 0;
  const pendingBookmarks = new Map();
  let pendingPreserve = null;
  const el = (tag, text, className) => { const node = doc.createElement(tag); if (text !== undefined) node.textContent = text; if (className) node.className = className; return node; };
  const panel = el(separateBookmarks ? 'section' : 'details', undefined, `camera-controls${separateBookmarks ? ' camera-controls-docked' : ''}`);
  const body = el('div', undefined, 'camera-controls-body'), status = el('p', '', 'camera-controls-status'); status.setAttribute('role', 'status');
  if (!separateBookmarks) panel.append(el('summary', '精确相机与视角书签'));
  panel.append(body); container.replaceChildren(panel);
  const bookPanel = el('section', undefined, 'camera-bookmarks');
  if (separateBookmarks) bookmarkContainer.replaceChildren(bookPanel);
  const bookStatus = separateBookmarks ? el('p', '', 'camera-controls-status') : status;
  bookStatus.setAttribute('role', 'status');
  const message = (text = '', error = false) => {
    for (const node of new Set([status, bookStatus])) { node.textContent = text; node.classList.toggle('camera-controls-error', error); }
  };
  const attempt = callback => { try { return callback(); } catch (error) { message(error.message || String(error), true); return null; } };
  const controls = [], bar = el('div', undefined, 'camera-controls-bar'), preserveLabel = el('label', undefined, 'camera-preserve');
  const preserveInput = el('input'); preserveInput.type = 'checkbox'; preserveInput.checked = true;
  preserveInput.setAttribute('aria-label', '增删文件时保持当前视角');
  preserveLabel.append(preserveInput, doc.createTextNode('增删文件时保持当前视角'));
  const heightLabel = el('span', '', 'camera-view-height'); bar.append(preserveLabel, heightLabel); body.append(bar);
  const grid = el('div', undefined, 'camera-controls-grid'); body.append(grid);
  const advanced = el('details', undefined, 'camera-advanced'), advancedGrid = el('div', undefined, 'camera-controls-grid');
  advanced.append(el('summary', '高级：平移与目标点'), advancedGrid); body.append(advanced);
  const specifications = [
    ['azimuth', '方位角（°）', .1], ['elevation', '仰角（°）', .1], ['zoom', '缩放倍率', .05],
    ['pan0', '水平平移', .1], ['pan1', '垂直平移', .1],
    ['target0', space === 'raw-world' ? '世界目标 X' : '排列目标 X', .1],
    ['target1', space === 'raw-world' ? '世界目标 Y' : '排列目标 Y', .1],
    ['target2', space === 'raw-world' ? '世界目标 Z' : '排列目标 Z', .1],
  ];
  const uiScene = () => getScene() || (space === 'lod-arrangement' ? {ids: [], scale: 'real'} : null);
  const available = () => {
    const viewer = getViewers()?.[0];
    return Boolean(viewer && (space === 'lod-arrangement' ? viewer.models?.length || uiScene()?.ids?.length : viewer.bounds));
  };
  function capture() { return available() ? captureCameraSnapshot(getViewers()[0], {space, scene: uiScene()}) : null; }
  function restore(snapshot, {checkScene = true} = {}) {
    if (!snapshot) return null;
    if (!available()) throw Error('请先加载数据，再应用相机');
    const value = applyCameraSnapshot(getViewers(), snapshot, {space, scene: uiScene(), checkScene, pauseSync});
    message('视角已应用。'); refresh(); return value;
  }
  function inputValue(snapshot, name) {
    return name.startsWith('pan') ? snapshot.camera.pan[Number(name.slice(3))] : name.startsWith('target') ? snapshot.camera.target[Number(name.slice(6))] : snapshot.camera[name];
  }
  function displayNumber(value, name) { return name.startsWith('target') ? String(value) : String(Number(value.toPrecision(12))); }
  function snapshotWithInput(name, raw) {
    const snapshot = capture(); if (!snapshot) throw Error('请先加载数据，再调整相机');
    if (!String(raw).trim()) throw Error('相机参数不能为空');
    const value = Number(raw);
    if (name.startsWith('pan')) snapshot.camera.pan[Number(name.slice(3))] = value;
    else if (name.startsWith('target')) snapshot.camera.target[Number(name.slice(6))] = value;
    else snapshot.camera[name] = value;
    return validateCameraSnapshot(snapshot, {space, scene: uiScene()});
  }
  function applyInput(name, raw) { restore(snapshotWithInput(name, raw)); message(''); }
  function sliderPosition(name, value, slider) {
    if (name === 'zoom') return Math.max(0, Math.min(1000, 1000 * Math.log(value / limits.minZoom) / Math.log(limits.maxZoom / limits.minZoom)));
    // +180 and -180 are identical; keep the right endpoint stable while dragging.
    if (name === 'azimuth' && value === -180 && Number(slider.value) === 180) return 180;
    return value;
  }
  function sliderNumber(name, raw) {
    const value = Number(raw), slider = sliders.get(name);
    if (!String(raw).trim() || !Number.isFinite(value) || value < Number(slider.min) || value > Number(slider.max)) throw Error('滑块数值超出范围');
    if (name !== 'zoom') return value;
    if (value === 0) return limits.minZoom;
    if (value === 1000) return limits.maxZoom;
    return limits.minZoom * Math.exp(value / 1000 * Math.log(limits.maxZoom / limits.minZoom));
  }
  for (const [name, label, step] of specifications) {
    const basic = ['azimuth', 'elevation', 'zoom'].includes(name);
    const group = el('div', undefined, `camera-number-field${basic ? ' camera-slider-field' : ''}`), caption = el('span', label), row = el('span', undefined, 'camera-number-row');
    const minus = el('button', '−'), input = el('input'), plus = el('button', '+');
    for (const button of [minus, plus]) { button.type = 'button'; button.setAttribute('aria-label', `${button === minus ? '减小' : '增大'}${label}`); }
    input.type = 'number'; input.step = String(step); input.setAttribute('aria-label', label); input.autocomplete = 'off';
    if (name === 'elevation') { input.min = String(limits.minElevation); input.max = '90'; }
    if (name === 'zoom') { input.min = String(limits.minZoom); input.max = String(limits.maxZoom); }
    input.addEventListener('input', () => {
      // Partial edits must leave the current camera intact; change reports errors.
      let snapshot; try { snapshot = snapshotWithInput(name, input.value); } catch { return; }
      attempt(() => { restore(snapshot); message(''); });
    });
    input.addEventListener('change', () => attempt(() => applyInput(name, input.value)));
    input.addEventListener('blur', scheduleRefresh);
    for (const [button, direction] of [[minus, -1], [plus, 1]]) button.addEventListener('click', event => {
      event.preventDefault(); attempt(() => {
        const snapshot = capture(); if (!snapshot) throw Error('请先加载数据，再调整相机');
        applyInput(name, Number((inputValue(snapshot, name) + direction * step).toPrecision(15)));
      });
    });
    row.append(minus, input, plus); group.append(caption, row);
    if (basic) {
      const slider = el('input', undefined, 'camera-slider'); slider.type = 'range';
      slider.min = String(name === 'zoom' ? 0 : name === 'azimuth' ? -180 : limits.minElevation);
      slider.max = String(name === 'zoom' ? 1000 : name === 'azimuth' ? 180 : 90);
      slider.step = name === 'zoom' ? '1' : '.1'; slider.setAttribute('aria-label', `${label}滑块`);
      slider.addEventListener('pointerdown', () => dragging.add(name));
      const finish = () => { dragging.delete(name); scheduleRefresh(); };
      for (const event of ['pointerup', 'pointercancel', 'lostpointercapture', 'change', 'blur']) slider.addEventListener(event, finish);
      slider.addEventListener('input', () => attempt(() => applyInput(name, sliderNumber(name, slider.value))));
      const endpoints = el('div', undefined, 'camera-slider-endpoints');
      endpoints.append(el('span', name === 'zoom' ? `${limits.minZoom}×` : `${slider.min}°`), el('span', name === 'zoom' ? `${limits.maxZoom}×` : `${slider.max}°`));
      group.append(slider, endpoints); sliders.set(name, slider); controls.push(slider);
    }
    (basic ? grid : advancedGrid).append(group); inputs.set(name, input); controls.push(minus, input, plus);
  }
  const help = el('p', space === 'raw-world'
    ? '平移按屏幕水平/垂直方向，单位与原坐标一致。目标点保留原始坐标精度。'
    : '目标点使用 LOD 排列坐标；书签适用于相同楼栋顺序和比例模式。', 'camera-controls-help');
  advanced.append(help);
  body.append(el('p', '拖动滑块可连续调整；数字输入与鼠标操作实时同步。缩放滑块采用对数刻度。', 'camera-controls-help'), status);
  // In the combined legacy layout bookmarks follow the camera, not precede it.
  if (!separateBookmarks) body.append(bookPanel);
  const bookHeading = el('div', undefined, 'camera-bookmark-heading'), bookCount = el('span', '', 'camera-bookmark-count');
  bookCount.setAttribute('aria-label', '已保存书签数量'); bookHeading.append(el('strong', '本机视角书签'), bookCount);
  const storageHelp = el('p', '保存在此浏览器，下次打开仍可使用。可导出 JSON 备份或转移到其他浏览器。', 'camera-bookmark-storage');
  const bookmarkName = el('input'), bookmarkSelect = el('select');
  bookmarkName.type = 'text'; bookmarkName.maxLength = 80; bookmarkName.placeholder = '输入视角名称'; bookmarkName.setAttribute('aria-label', '视角书签名称');
  bookmarkSelect.size = 5; bookmarkSelect.setAttribute('aria-label', '已保存视角');
  const bookmarkMeta = el('p', '', 'camera-bookmark-meta'); bookmarkMeta.setAttribute('aria-label', '选中书签信息');
  bookPanel.append(bookHeading, storageHelp, bookmarkSelect, bookmarkMeta, bookmarkName);
  const actions = el('div', undefined, 'camera-bookmark-actions');
  const action = text => { const button = el('button', text); button.type = 'button'; actions.append(button); return button; };
  const saveButton = action('保存新书签'), loadButton = action('加载所选'), updateButton = action('更新视角'), renameButton = action('重命名'), deleteButton = action('删除所选');
  const files = el('div', undefined, 'camera-bookmark-files');
  const exportButton = el('button', '导出 JSON'), importButton = el('button', '导入 JSON');
  exportButton.type = importButton.type = 'button'; files.append(exportButton, importButton);
  const importInput = el('input'); importInput.type = 'file'; importInput.accept = '.json,application/json'; importInput.hidden = true;
  bookPanel.append(actions, files, importInput); if (separateBookmarks) bookPanel.append(bookStatus);
  function storageUnavailable() {
    storageHelp.textContent = '当前浏览器无法持久保存；本次书签仍可使用，请导出 JSON 备份。';
    message(storageHelp.textContent, true);
  }
  function syncStored({notifyDeleted = true} = {}) {
    try {
      const stored = win.localStorage.getItem(key);
      const latest = stored ? parseCameraBookmarks(stored, space) : {bookmarks: [], preserveView: true};
      // Rebase only unsaved local edits, never this panel's entire cached array.
      const merged = new Map(latest.bookmarks.map(bookmark => [bookmark.id, bookmark]));
      for (const [id, bookmark] of pendingBookmarks) { if (bookmark) merged.set(id, bookmark); else merged.delete(id); }
      bookmarks = [...merged.values()];
      preserveView = pendingPreserve ?? latest.preserveView; preserveInput.checked = preserveView;
      const deleted = selectedBookmark && !merged.has(selectedBookmark);
      updateBookmarks();
      // Keep the name input untouched: it may contain an unfinished draft.
      if (deleted && notifyDeleted) message('所选书签已在另一页面删除，请重新选择；当前视角未改变。', true);
      return true;
    } catch { storageUnavailable(); return false; }
  }
  function persist() {
    // Read again at the write boundary, including after asynchronous imports.
    // When reading fails, do not overwrite records we cannot safely reconcile.
    if (!syncStored()) return false;
    try {
      win.localStorage.setItem(key, serializeCameraBookmarks(bookmarks, space, preserveView));
      pendingBookmarks.clear(); pendingPreserve = null;
      storageHelp.textContent = '保存在此浏览器，下次打开仍可使用。可导出 JSON 备份或转移到其他浏览器。'; return true;
    } catch { storageUnavailable(); return false; }
  }
  function updateBookmarks() {
    bookmarkSelect.replaceChildren();
    if (!bookmarks.length) { const empty = el('option', '暂无书签'); empty.value = ''; bookmarkSelect.append(empty); }
    for (const bookmark of bookmarks) { const option = el('option', bookmark.name); option.value = bookmark.id; bookmarkSelect.append(option); }
    const selected = bookmarks.find(bookmark => bookmark.id === selectedBookmark);
    if (!selected) selectedBookmark = '';
    bookmarkSelect.value = selectedBookmark;
    bookCount.textContent = `${bookmarks.length} / ${CAMERA_MAX_BOOKMARKS}`;
    bookmarkMeta.textContent = selected ? `${selected.name}\n更新：${selected.updatedAt ? new Date(selected.updatedAt).toLocaleString('zh-CN', {hour12: false}) : '未记录（旧版书签）'}` : '选择书签后可加载、更新、重命名或删除。';
    loadButton.disabled = updateButton.disabled = !available() || !selectedBookmark;
    renameButton.disabled = deleteButton.disabled = !selectedBookmark; exportButton.disabled = !bookmarks.length;
  }
  function scheduleRefresh() {
    if (disposed || frame !== null) return;
    frame = win.requestAnimationFrame(() => { frame = null; refresh(); });
  }
  function watchViewers() {
    for (const viewer of getViewers() || []) {
      if (watches.has(viewer) || typeof viewer.render !== 'function') continue;
      const original = viewer.render;
      const wrapped = function(...args) { const result = original.apply(this, args); scheduleRefresh(); return result; };
      watches.set(viewer, {original, wrapped}); viewer.render = wrapped;
    }
  }
  function refresh() {
    if (disposed) return;
    watchViewers(); const snapshot = attempt(capture), enabled = Boolean(snapshot);
    controls.forEach(control => { control.disabled = !enabled; }); saveButton.disabled = !enabled;
    if (snapshot) {
      for (const [name, input] of inputs) if (doc.activeElement !== input) input.value = displayNumber(inputValue(snapshot, name), name);
      for (const [name, slider] of sliders) {
        if (!dragging.has(name)) slider.value = String(sliderPosition(name, inputValue(snapshot, name), slider));
        slider.setAttribute('aria-valuetext', `${displayNumber(inputValue(snapshot, name), name)}${name === 'zoom' ? ' 倍' : ' 度'}`);
      }
      heightLabel.textContent = `可视高度 ${(snapshot.camera.baseHeight / snapshot.camera.zoom).toPrecision(6)}（原坐标单位）`;
    } else {
      dragging.clear(); for (const input of inputs.values()) if (doc.activeElement !== input) input.value = '';
      heightLabel.textContent = '加载数据后可调整';
    }
    loadButton.disabled = updateButton.disabled = !enabled || !selectedBookmark;
  }
  const finishDragging = () => { if (dragging.size) { dragging.clear(); scheduleRefresh(); } };
  win.addEventListener?.('pointerup', finishDragging); win.addEventListener?.('pointercancel', finishDragging);
  function freshId() {
    let id; do { id = win.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}-${++idCounter}`; }
    while (bookmarks.some(bookmark => bookmark.id === id)); return id;
  }
  function validName() {
    const name = bookmarkName.value.trim(); if (!name || name.length > 80) throw Error('请填写 1–80 个字符的书签名称'); return name;
  }
  function uniqueName(name) {
    let result = name, number = 2;
    while (bookmarks.some(bookmark => bookmark.name === result)) { const suffix = ` (${number++})`; result = name.slice(0, 80 - suffix.length) + suffix; }
    return result;
  }
  preserveInput.addEventListener('change', () => {
    const requested = preserveInput.checked; syncStored();
    pendingPreserve = requested; preserveView = requested; preserveInput.checked = requested; persist();
  });
  bookmarkSelect.addEventListener('change', () => {
    selectedBookmark = bookmarkSelect.value;
    const selected = bookmarks.find(bookmark => bookmark.id === selectedBookmark); if (selected) bookmarkName.value = selected.name;
    updateBookmarks();
  });
  saveButton.addEventListener('click', () => attempt(() => {
    syncStored();
    const snapshot = capture(); if (!snapshot) throw Error('请先加载数据，再保存视角');
    if (bookmarks.length >= CAMERA_MAX_BOOKMARKS) throw Error('最多保存 100 个书签，请先删除不需要的视角');
    const name = uniqueName(validName()), record = {id: freshId(), name, snapshot, updatedAt: new Date().toISOString()};
    bookmarks.push(record); pendingBookmarks.set(record.id, record); selectedBookmark = record.id; bookmarkName.value = name; updateBookmarks();
    if (persist()) message(`已保存新书签“${name}”，下次打开仍可使用。`);
  }));
  loadButton.addEventListener('click', () => attempt(() => {
    syncStored();
    const bookmark = bookmarks.find(record => record.id === selectedBookmark); if (bookmark) restore(bookmark.snapshot);
  }));
  updateButton.addEventListener('click', () => attempt(() => {
    syncStored();
    const bookmark = bookmarks.find(record => record.id === selectedBookmark); if (!bookmark) return;
    const snapshot = capture(); if (!snapshot) throw Error('请先加载数据，再更新视角');
    bookmark.snapshot = snapshot; bookmark.updatedAt = new Date().toISOString(); pendingBookmarks.set(bookmark.id, bookmark); updateBookmarks();
    if (persist()) message(`已更新“${bookmark.name}”的视角。`);
  }));
  renameButton.addEventListener('click', () => attempt(() => {
    syncStored();
    const bookmark = bookmarks.find(record => record.id === selectedBookmark); if (!bookmark) return;
    const name = validName();
    if (bookmarks.some(record => record.id !== bookmark.id && record.name === name)) throw Error('已有同名书签，请使用其他名称');
    bookmark.name = name; bookmark.updatedAt = new Date().toISOString(); pendingBookmarks.set(bookmark.id, bookmark); updateBookmarks();
    if (persist()) message(`已重命名为“${name}”。`);
  }));
  deleteButton.addEventListener('click', () => {
    syncStored(); if (!selectedBookmark) return;
    pendingBookmarks.set(selectedBookmark, null);
    bookmarks = bookmarks.filter(bookmark => bookmark.id !== selectedBookmark); selectedBookmark = ''; bookmarkName.value = ''; updateBookmarks();
    if (persist()) message('书签已删除。');
  });
  exportButton.addEventListener('click', () => attempt(() => {
    syncStored();
    const blob = new Blob([serializeCameraBookmarks(bookmarks, space, preserveView)], {type: 'application/json'});
    const url = win.URL.createObjectURL(blob), link = el('a'); link.href = url; link.download = `BuildingWebViewer-camera-${space}.json`; link.click();
    win.setTimeout(() => win.URL.revokeObjectURL(url), 1000); message('相机书签 JSON 已导出，不含模型数据。');
  }));
  importButton.addEventListener('click', () => importInput.click());
  importInput.addEventListener('change', async () => {
    const file = importInput.files?.[0]; importInput.value = ''; if (!file) return;
    try {
      if (file.size > 1024 * 1024) throw Error('相机 JSON 超过 1 MB，请检查是否选择了正确文件');
      const incoming = parseCameraBookmarks(await file.text(), space);
      if (disposed) return;
      syncStored();
      if (bookmarks.length + incoming.bookmarks.length > CAMERA_MAX_BOOKMARKS) throw Error('导入后超过 100 个书签，请先删除不需要的视角');
      for (const bookmark of incoming.bookmarks) {
        const record = {...bookmark, name: uniqueName(bookmark.name), id: freshId(), updatedAt: bookmark.updatedAt || new Date().toISOString()};
        bookmarks.push(record); pendingBookmarks.set(record.id, record);
      }
      selectedBookmark = incoming.bookmarks.length ? bookmarks.at(-1).id : selectedBookmark;
      if (selectedBookmark) bookmarkName.value = bookmarks.find(bookmark => bookmark.id === selectedBookmark).name;
      updateBookmarks(); if (persist()) message(`已导入 ${incoming.bookmarks.length} 个书签；选择后点击“加载所选”应用。`);
    } catch (error) { message(error.message || String(error), true); }
  });
  const onStorage = event => {
    if (!disposed && (event.key === key || event.key === null)) syncStored();
  };
  win.addEventListener?.('storage', onStorage);
  syncStored({notifyDeleted: false});
  preserveInput.checked = preserveView; updateBookmarks(); refresh();
  return {
    get preserveView() { return preserveView; }, capture, restore, refresh,
    destroy() {
      disposed = true; if (frame !== null) win.cancelAnimationFrame(frame);
      for (const [viewer, {original, wrapped}] of watches) if (viewer.render === wrapped) viewer.render = original;
      win.removeEventListener?.('storage', onStorage);
      win.removeEventListener?.('pointerup', finishDragging); win.removeEventListener?.('pointercancel', finishDragging);
      panel.remove(); if (separateBookmarks) bookPanel.remove(); watches.clear(); dragging.clear();
    },
  };
}


// Source: renderer.js

/** Local, dependency-free mesh renderer. Building placement is synthetic; geometry and scale are preserved. */
const DEG = Math.PI / 180;
const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const clamp = (value, low, high) => Math.max(low, Math.min(high, value));
const PALETTE = [[.39, .57, .67], [.64, .61, .46], [.50, .63, .58], [.62, .52, .64], [.67, .53, .43], [.45, .61, .72], [.65, .61, .69], [.55, .66, .46]];
const VERTEX_SHADER = `
precision highp float;
attribute vec3 position;
attribute vec3 normal;
attribute vec3 buildingColor;
attribute float vertexHeight;
uniform vec2 heightTransform;
varying highp float heightValue;
uniform mat4 matrix;
uniform mediump int kind;
uniform mediump int colorByBuilding;
varying vec4 color;
void main() {
  gl_Position = matrix * vec4(position, 1.0);
  heightValue = vertexHeight * heightTransform.y + heightTransform.x;
  if (kind == 0) {
    vec3 base = abs(normal.z) > .22 ? vec3(.46, .59, .67) : vec3(.91, .89, .84);
    if (colorByBuilding == 1) base = buildingColor * (abs(normal.z) > .22 ? .86 : 1.13);
    float light = .75 + .25 * abs(dot(normal, normalize(vec3(-.5, -.7, 1.1))));
    color = vec4(base * light, 1.0);
  } else if (kind == 2) {
    color = vec4(.67, .71, .74, .24);
  } else if (kind == 3) {
    color = vec4(.23, .36, .43, .64);
  } else {
    color = vec4(.23, .31, .36, .65);
  }
}`;
const FRAGMENT_SHADER = `
precision mediump float;
varying vec4 color;
varying highp float heightValue;
uniform mediump int kind;
uniform mediump int colorByBuilding;
${PALETTE_GLSL}
void main() {
  gl_FragColor = colorByBuilding == 2 && (kind == 0 || kind == 3)
    ? vec4(paletteColor(heightValue), kind == 0 ? 1.0 : .9) : color;
}`;

class MeshViewer {
  constructor(canvas, { onLabels = () => {}, onError = () => {}, onViewChange = () => {} } = {}) {
    this.canvas = canvas;
    this.onLabels = onLabels;
    this.onError = onError;
    this.onViewChange = onViewChange;
    this.options = { mode: 'solid', edges: true, colors: 'surface', grid: true, labels: true, scale: 'real', palette: 'current', reverse: false, range: null };
    this.camera = { elevation: 38, azimuth: -55, zoom: 1, pan: [0, 0] };
    this.baseHeight = 30;
    this.sceneBounds = [[-5, -5, 0], [5, 5, 10]];
    this.target = [0, 0, 5];
    this.models = [];
    this.labelAnchors = [];
    this.buffers = {};
    this.triangleCount = 0;
    this.disposed = false;
    this.contextLost = false;
    this.frame = null;
    this.listeners = [];
    try {
      this.gl = canvas.getContext('webgl', { antialias: true, alpha: false, preserveDrawingBuffer: true });
      if (!this.gl) throw new Error('此浏览器无法启用 WebGL，请检查浏览器的硬件加速设置。');
      this.initGL();
    } catch (error) {
      this.onError(error.message);
      throw error;
    }
    this.installEvents();
    this.resizeObserver = new ResizeObserver(() => this.requestRender());
    this.resizeObserver.observe(canvas);
    this.render();
  }

  initGL() {
    const gl = this.gl;
    const compile = (type, source) => {
      const shader = gl.createShader(type);
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        const message = gl.getShaderInfoLog(shader);
        gl.deleteShader(shader);
        throw new Error(`WebGL 着色器编译失败：${message}`);
      }
      return shader;
    };
    const vertex = compile(gl.VERTEX_SHADER, VERTEX_SHADER);
    const fragment = compile(gl.FRAGMENT_SHADER, FRAGMENT_SHADER);
    const program = gl.createProgram();
    gl.attachShader(program, vertex);
    gl.attachShader(program, fragment);
    gl.linkProgram(program);
    gl.deleteShader(vertex);
    gl.deleteShader(fragment);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      const message = gl.getProgramInfoLog(program);
      gl.deleteProgram(program);
      throw new Error(`WebGL 程序链接失败：${message}`);
    }
    this.program = program;
    this.locations = {
      position: gl.getAttribLocation(program, 'position'),
      normal: gl.getAttribLocation(program, 'normal'),
      buildingColor: gl.getAttribLocation(program, 'buildingColor'),
      vertexHeight: gl.getAttribLocation(program, 'vertexHeight'),
      heightTransform: gl.getUniformLocation(program, 'heightTransform'),
      colorStops: gl.getUniformLocation(program, 'colorStops[0]'),
      matrix: gl.getUniformLocation(program, 'matrix'),
      kind: gl.getUniformLocation(program, 'kind'),
      colorByBuilding: gl.getUniformLocation(program, 'colorByBuilding'),
    };
  }

  installEvents() {
    const listen = (name, fn, options) => {
      this.canvas.addEventListener(name, fn, options);
      this.listeners.push([name, fn, options]);
    };
    this.canvas.style.touchAction = 'none';
    listen('contextmenu', event => event.preventDefault());
    listen('pointerdown', event => {
      if (event.button !== 0 && event.button !== 2 && event.button !== 1) return;
      event.preventDefault();
      this.canvas.setPointerCapture(event.pointerId);
      this.drag = { pointerId: event.pointerId, x: event.clientX, y: event.clientY,
        pan: event.button !== 0 || event.shiftKey };
      this.canvas.style.cursor = 'grabbing';
    });
    listen('pointermove', event => {
      if (!this.drag || this.drag.pointerId !== event.pointerId) return;
      const dx = event.clientX - this.drag.x, dy = event.clientY - this.drag.y;
      this.drag.x = event.clientX;
      this.drag.y = event.clientY;
      if (this.drag.pan || event.shiftKey) {
        const pixelSize = this.baseHeight / this.camera.zoom / Math.max(1, this.canvas.clientHeight);
        this.camera.pan[0] -= dx * pixelSize;
        this.camera.pan[1] += dy * pixelSize;
      } else {
        this.camera.azimuth = (this.camera.azimuth - dx * .35) % 360;
        this.camera.elevation = clamp(this.camera.elevation + dy * .3, 0, 90);
      }
      this.requestRender();
    });
    const finish = event => {
      if (this.drag?.pointerId !== event.pointerId) return;
      this.drag = null;
      this.canvas.style.cursor = 'grab';
      if (this.canvas.hasPointerCapture(event.pointerId)) this.canvas.releasePointerCapture(event.pointerId);
    };
    listen('pointerup', finish);
    listen('pointercancel', finish);
    listen('lostpointercapture', finish);
    listen('wheel', event => {
      event.preventDefault();
      const delta = event.deltaY * (event.deltaMode === 1 ? 16 : event.deltaMode === 2 ? this.canvas.clientHeight : 1);
      this.zoomBy(Math.exp(-clamp(delta, -500, 500) * .0015));
    }, { passive: false });
    listen('webglcontextlost', event => {
      event.preventDefault();
      this.contextLost = true;
      this.onError('WebGL 显示上下文暂时丢失，正在等待浏览器恢复。');
    });
    listen('webglcontextrestored', () => {
      this.contextLost = false;
      try {
        this.buffers = {};
        this.initGL();
        this.setModels(this.models);
        this.onError('');
      } catch (error) { this.onError(error.message); }
    });
  }

  makeBuffer(values) {
    const gl = this.gl, buffer = gl.createBuffer();
    if (!buffer) throw new Error('无法分配 WebGL 缓冲区，请减少同时查看的楼栋数量。');
    gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(values), gl.STATIC_DRAW);
    if (gl.getError() === gl.OUT_OF_MEMORY) {
      gl.deleteBuffer(buffer);
      throw new Error('显存不足，请减少同时查看的楼栋数量。');
    }
    return { buffer, count: values.length / 10 };
  }

  setModels(models) {
    if (!Array.isArray(models)) throw new TypeError('setModels 需要模型数组。');
    const prepared = models.map(model => {
      if (!model.vertices?.length || !Array.isArray(model.faces)) throw new Error(`楼栋 ${model.id} 缺少有效网格。`);
      const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
      for (const point of model.vertices) {
        if (point.length < 3 || !point.slice(0, 3).every(Number.isFinite)) throw new Error(`楼栋 ${model.id} 包含无效坐标。`);
        for (let i = 0; i < 3; i++) { min[i] = Math.min(min[i], point[i]); max[i] = Math.max(max[i], point[i]); }
      }
      const extent = Math.max(...max.map((value, i) => value - min[i]));
      const scale = this.options.scale === 'normalized' && extent > 0 ? 30 / extent : 1;
      return { model, min, max, scale, width: (max[0] - min[0]) * scale, depth: (max[1] - min[1]) * scale };
    });
    const columns = Math.ceil(Math.sqrt(prepared.length)), rows = Math.ceil(prepared.length / (columns || 1));
    const widths = Array(columns).fill(0), depths = Array(rows).fill(0);
    for (let i = 0; i < prepared.length; i++) {
      widths[i % columns] = Math.max(widths[i % columns], prepared[i].width);
      depths[Math.floor(i / columns)] = Math.max(depths[Math.floor(i / columns)], prepared[i].depth);
    }
    const typical = prepared.map(item => Math.max(item.width, item.depth)).sort((a, b) => a - b);
    const gap = Math.max(2, (typical[Math.floor(typical.length / 2)] || 10) * .35);
    const totalWidth = widths.reduce((sum, value) => sum + value, 0) + Math.max(0, columns - 1) * gap;
    const totalDepth = depths.reduce((sum, value) => sum + value, 0) + Math.max(0, rows - 1) * gap;
    const centers = values => {
      let offset = 0;
      return values.map(value => { const center = offset + value / 2; offset += value + gap; return center; });
    };
    const xCenters = centers(widths), yCenters = centers(depths);
    const triangles = [], featureEdges = [], allEdges = [], labels = [];
    let maxHeight = 0, maxOriginalHeight = 0;
    const vertexOut = (array, position, normal, color, height = 0) => array.push(...position, ...normal, ...color, height);
    const featureCosine = Math.cos(10 * DEG);
    for (let modelIndex = 0; modelIndex < prepared.length; modelIndex++) {
      const { model, min, max, scale } = prepared[modelIndex];
      const cx = xCenters[modelIndex % columns] - totalWidth / 2;
      const cy = totalDepth / 2 - yCenters[Math.floor(modelIndex / columns)];
      const vertices = model.vertices.map(v => [(v[0] - (min[0] + max[0]) / 2) * scale + cx, (v[1] - (min[1] + max[1]) / 2) * scale + cy, (v[2] - min[2]) * scale]);
      const height = (max[2] - min[2]) * scale;
      maxHeight = Math.max(maxHeight, height);
      maxOriginalHeight = Math.max(maxOriginalHeight, max[2] - min[2]);
      labels.push({ id: model.id, bounds: [[cx - prepared[modelIndex].width / 2, cy - prepared[modelIndex].depth / 2, 0],
        [cx + prepared[modelIndex].width / 2, cy + prepared[modelIndex].depth / 2, height]] });
      let hash = 0;
      for (const char of String(model.id)) hash = ((hash * 31) + char.charCodeAt(0)) >>> 0;
      const color = PALETTE[hash % PALETTE.length];
      // Exact-coordinate welding also handles OBJ files that duplicate vertices at material/normal seams.
      const unique = new Map();
      const welded = vertices.map((v, index) => { const key = v.join(','); if (!unique.has(key)) unique.set(key, index); return unique.get(key); });
      const edges = new Map();
      for (const face of model.faces) {
        if (face.length !== 3 || !face.every(index => Number.isInteger(index) && index >= 0 && index < vertices.length)) {
          throw new Error(`楼栋 ${model.id} 包含无效三角面。`);
        }
        const [a, b, c] = face.map(index => vertices[index]);
        const ab = b.map((value, i) => value - a[i]), ac = c.map((value, i) => value - a[i]);
        const normal = [ab[1] * ac[2] - ab[2] * ac[1], ab[2] * ac[0] - ab[0] * ac[2], ab[0] * ac[1] - ab[1] * ac[0]];
        const length = Math.hypot(...normal);
        if (length < 1e-12) continue;
        for (let i = 0; i < 3; i++) normal[i] /= length;
        for (const point of [a, b, c]) vertexOut(triangles, point, normal, color, point[2] / scale);
        for (let i = 0; i < 3; i++) {
          const ai = welded[face[i]], bi = welded[face[(i + 1) % 3]];
          const key = ai < bi ? `${ai}:${bi}` : `${bi}:${ai}`;
          if (!edges.has(key)) edges.set(key, { a: vertices[ai], b: vertices[bi], normals: [] });
          edges.get(key).normals.push(normal);
        }
      }
      for (const edge of edges.values()) {
        vertexOut(allEdges, edge.a, [0, 0, 1], color, edge.a[2] / scale);
        vertexOut(allEdges, edge.b, [0, 0, 1], color, edge.b[2] / scale);
        const normals = edge.normals;
        const feature = normals.length !== 2 || Math.abs(dot(normals[0], normals[1])) < featureCosine;
        if (feature) {
          vertexOut(featureEdges, edge.a, [0, 0, 1], color, edge.a[2] / scale);
          vertexOut(featureEdges, edge.b, [0, 0, 1], color, edge.b[2] / scale);
        }
      }
    }
    const nextBuffers = {};
    try {
      nextBuffers.triangles = this.makeBuffer(triangles);
      nextBuffers.featureEdges = this.makeBuffer(featureEdges);
      nextBuffers.allEdges = this.makeBuffer(allEdges);
      const grid = [], span = Math.max(totalWidth, totalDepth, 10) * .7 + gap;
      const roughStep = span / 15, power = Math.pow(10, Math.floor(Math.log10(roughStep)));
      const unit = roughStep / power;
      const step = (unit <= 1 ? 1 : unit <= 2 ? 2 : unit <= 5 ? 5 : 10) * power;
      const gridExtent = Math.ceil(span / step) * step;
      const z = -Math.max(.005, maxHeight * .0001);
      for (let k = -Math.floor(gridExtent / step); k <= Math.floor(gridExtent / step); k++) {
        for (const point of [[k * step, -gridExtent, z], [k * step, gridExtent, z], [-gridExtent, k * step, z], [gridExtent, k * step, z]]) vertexOut(grid, point, [0, 0, 1], [1, 1, 1]);
      }
      nextBuffers.grid = this.makeBuffer(grid);
    } catch (error) {
      for (const item of Object.values(nextBuffers)) this.gl.deleteBuffer(item.buffer);
      this.onError(error.message);
      throw error;
    }
    for (const item of Object.values(this.buffers)) this.gl.deleteBuffer(item.buffer);
    this.buffers = nextBuffers;
    this.models = models;
    this.labelAnchors = labels;
    this.triangleCount = triangles.length / 30;
    this.heightRange = models.length ? {min: 0, max: maxOriginalHeight} : null;
    this.sceneBounds = prepared.length ? [[-totalWidth / 2, -totalDepth / 2, 0], [totalWidth / 2, totalDepth / 2, maxHeight]] : [[-5, -5, 0], [5, 5, 10]];
    this.target = prepared.length ? [0, 0, maxHeight / 2] : [0, 0, 5];
    this.fit();
  }

  setOptions(options) {
    const next = { ...this.options, ...options };
    if (!['solid', 'wire', 'solid-wire'].includes(next.mode)) throw new Error(`不支持的显示模式：${next.mode}`);
    if (!['surface', 'building', 'height'].includes(next.colors)) throw new Error(`不支持的配色模式：${next.colors}`);
    if (!['real', 'normalized'].includes(next.scale)) throw new Error(`不支持的比例模式：${next.scale}`);
    next.palette ||= 'current'; next.reverse = !!next.reverse; next.range = next.range ? {...next.range} : null;
    validatePaletteOptions(next);
    const rebuild = next.scale !== this.options.scale;
    this.options = next;
    if (rebuild) this.setModels(this.models);
    else this.render();
  }

  setView(view) {
    const views = { iso: [38, -55], top: [90, -90], front: [0, -90] };
    if (!views[view]) throw new Error(`不支持的视角：${view}`);
    [this.camera.elevation, this.camera.azimuth] = views[view];
    this.fit();
  }

  basis() {
    const e = this.camera.elevation * DEG, a = this.camera.azimuth * DEG;
    return [[-Math.sin(a), Math.cos(a), 0], [-Math.cos(a) * Math.sin(e), -Math.sin(a) * Math.sin(e), Math.cos(e)], [Math.cos(a) * Math.cos(e), Math.sin(a) * Math.cos(e), Math.sin(e)]];
  }

  fit() {
    const [right, up] = this.basis(), [min, max] = this.sceneBounds;
    let xMin = Infinity, xMax = -Infinity, yMin = Infinity, yMax = -Infinity;
    for (const x of [min[0], max[0]]) for (const y of [min[1], max[1]]) for (const z of [min[2], max[2]]) {
      const point = [x, y, z], projectedX = dot(point, right), projectedY = dot(point, up);
      xMin = Math.min(xMin, projectedX); xMax = Math.max(xMax, projectedX);
      yMin = Math.min(yMin, projectedY); yMax = Math.max(yMax, projectedY);
    }
    const aspect = Math.max(1, this.canvas.clientWidth) / Math.max(1, this.canvas.clientHeight);
    this.baseHeight = Math.max(2, yMax - yMin, (xMax - xMin) / aspect) * 1.3;
    this.camera.zoom = 1;
    this.camera.pan = [0, 0];
    this.render();
  }

  zoomBy(factor) {
    if (!Number.isFinite(factor) || factor <= 0) return;
    this.camera.zoom = clamp(this.camera.zoom * factor, .15, 30);
    this.render();
  }

  matrix() {
    const [r, u, t] = this.basis();
    const aspect = this.canvas.width / Math.max(1, this.canvas.height);
    const height = this.baseHeight / this.camera.zoom, width = height * aspect;
    const cx = dot(this.target, r) + this.camera.pan[0], cy = dot(this.target, u) + this.camera.pan[1];
    const depth = Math.max(10, Math.hypot(...this.sceneBounds[1].map((v, i) => v - this.sceneBounds[0][i]))) * 4;
    return new Float32Array([2 * r[0] / width, 2 * u[0] / height, -t[0] / depth, 0,
      2 * r[1] / width, 2 * u[1] / height, -t[1] / depth, 0,
      2 * r[2] / width, 2 * u[2] / height, -t[2] / depth, 0,
      -2 * cx / width, -2 * cy / height, dot(this.target, t) / depth, 1]);
  }

  requestRender() {
    if (this.frame !== null || this.disposed) return;
    this.frame = requestAnimationFrame(() => { this.frame = null; this.render(); });
  }

  render() {
    if (this.disposed || this.contextLost) return;
    if (this.frame !== null) { cancelAnimationFrame(this.frame); this.frame = null; }
    const canvas = this.canvas, gl = this.gl, rect = canvas.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const width = Math.max(1, Math.round(rect.width * dpr)), height = Math.max(1, Math.round(rect.height * dpr));
    if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; }
    const matrix = this.matrix(), loc = this.locations;
    gl.viewport(0, 0, width, height);
    gl.clearColor(.951, .960, .965, 1);
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    gl.useProgram(this.program);
    gl.uniformMatrix4fv(loc.matrix, false, matrix);
    gl.uniform1i(loc.colorByBuilding, this.options.colors === 'height' ? 2 : this.options.colors === 'building' ? 1 : 0);
    gl.uniform3fv(loc.colorStops, paletteUniforms(this.options.palette, this.options.reverse));
    const range = this.options.range || this.heightRange, span = range ? range.max - range.min : 0;
    gl.uniform2f(loc.heightTransform, span > 0 ? -range.min / span : .5, span > 0 ? 1 / span : 0);
    for (const location of [loc.position, loc.normal, loc.buildingColor, loc.vertexHeight]) gl.enableVertexAttribArray(location);
    gl.disable(gl.CULL_FACE); // Input meshes may use mixed winding; both sides must remain visible.
    gl.enable(gl.DEPTH_TEST);
    gl.depthFunc(gl.LEQUAL);
    gl.enable(gl.BLEND);
    gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
    const draw = (buffer, kind, primitive) => {
      if (!buffer?.count) return;
      gl.bindBuffer(gl.ARRAY_BUFFER, buffer.buffer);
      gl.vertexAttribPointer(loc.position, 3, gl.FLOAT, false, 40, 0);
      gl.vertexAttribPointer(loc.normal, 3, gl.FLOAT, false, 40, 12);
      gl.vertexAttribPointer(loc.buildingColor, 3, gl.FLOAT, false, 40, 24);
      gl.vertexAttribPointer(loc.vertexHeight, 1, gl.FLOAT, false, 40, 36);
      gl.uniform1i(loc.kind, kind);
      gl.drawArrays(primitive, 0, buffer.count);
    };
    if (this.options.grid && this.models.length) draw(this.buffers.grid, 2, gl.LINES);
    if (this.options.mode !== 'wire') {
      gl.enable(gl.POLYGON_OFFSET_FILL);
      gl.polygonOffset(1, 1);
      draw(this.buffers.triangles, 0, gl.TRIANGLES);
      gl.disable(gl.POLYGON_OFFSET_FILL);
    }
    if (this.options.mode === 'wire' || this.options.mode === 'solid-wire') draw(this.buffers.allEdges, 3, gl.LINES);
    else if (this.options.edges) draw(this.buffers.featureEdges, 1, gl.LINES);
    this.onLabels(this.options.labels ? this.labelAnchors.map(({ id, bounds: [min, max] }) => {
      let xMin = Infinity, xMax = -Infinity, yMin = Infinity;
      for (const px of [min[0], max[0]]) for (const py of [min[1], max[1]]) for (const pz of [min[2], max[2]]) {
        const x = matrix[0] * px + matrix[4] * py + matrix[8] * pz + matrix[12];
        const y = matrix[1] * px + matrix[5] * py + matrix[9] * pz + matrix[13];
        xMin = Math.min(xMin, x); xMax = Math.max(xMax, x); yMin = Math.min(yMin, y);
      }
      const x = (xMin + xMax) / 2;
      const screenY = (1 - yMin) * rect.height / 2 + 8;
      return { id, x: (x + 1) * rect.width / 2, y: screenY,
        visible: x > -.99 && x < .99 && screenY >= 0 && screenY < rect.height - 24 };
    }) : []);
    this.onViewChange?.(this.getState());
  }

  getState() {
    return { buildingCount: this.models.length, triangleCount: this.triangleCount,
      featureEdgeCount: (this.buffers.featureEdges?.count || 0) / 2,
      allEdgeCount: (this.buffers.allEdges?.count || 0) / 2,
      syntheticArrangement: true, heightMeaning: 'height-above-building-min-z',
      dataRange: this.heightRange ? {...this.heightRange} : null,
      colorRange: this.options.colors === 'height' && this.heightRange ? {...(this.options.range || this.heightRange)} : null, camera: { ...this.camera, pan: [...this.camera.pan], baseHeight: this.baseHeight },
      options: { ...this.options }, bounds: this.sceneBounds.map(point => [...point]) };
  }

  destroy() {
    this.disposed = true;
    if (this.frame !== null) cancelAnimationFrame(this.frame);
    this.resizeObserver.disconnect();
    for (const [name, fn, options] of this.listeners) this.canvas.removeEventListener(name, fn, options);
    for (const item of Object.values(this.buffers)) this.gl.deleteBuffer(item.buffer);
    this.gl.deleteProgram(this.program);
    this.onLabels([]);
  }
}


// Source: obj-parser.js
/** Parse triangular OBJ geometry without altering source coordinates. */
function parseOBJ(text, id, bytes = 0) {
  const vertices = [], faces = [];
  const bounds = [[Infinity, Infinity, Infinity], [-Infinity, -Infinity, -Infinity]];
  let lineNumber = 0;
  for (const line of text.split(/\r?\n/)) {
    lineNumber++;
    const tokens = line.split('#')[0].trim().split(/\s+/);
    if (tokens[0] === 'v') {
      const vertex = tokens.slice(1, 4).map(Number);
      if (vertex.length !== 3 || vertex.some(v => !Number.isFinite(v))) throw Error(`第 ${lineNumber} 行顶点坐标无效`);
      vertices.push(vertex);
      vertex.forEach((value, axis) => { bounds[0][axis] = Math.min(bounds[0][axis], value); bounds[1][axis] = Math.max(bounds[1][axis], value); });
    } else if (tokens[0] === 'f') {
      if (tokens.length !== 4) throw Error(`第 ${lineNumber} 行不是三角面，当前查看器需要三角化 OBJ`);
      faces.push(tokens.slice(1).map(token => {
        const index = Number(token.split('/')[0]);
        if (!Number.isSafeInteger(index) || index === 0) throw Error(`第 ${lineNumber} 行面索引无效`);
        const resolved = index > 0 ? index - 1 : vertices.length + index;
        if (resolved < 0) throw Error(`第 ${lineNumber} 行面索引越界`);
        return resolved;
      }));
    }
  }
  if (!vertices.length || !faces.length) throw Error('OBJ 中没有可显示的顶点和三角面');
  if (faces.some(face => face.some(index => index >= vertices.length))) throw Error('OBJ 面索引超出顶点范围');
  return {id, vertices, faces, bounds, stats: {vertices: vertices.length, triangles: faces.length, bytes}};
}


// Source: app.js





const $ = (id) => document.getElementById(id);
const MAX_SELECTED = 24, PAGE_SIZE = 50;
const number = (value) => Number(value).toLocaleString('zh-CN');
let catalog = [], catalogById = new Map(), selected = new Set(), page = 0;
let cache = new Map(), currentModels = [], viewer, generation = 0, controller;
let labelElements = new Map(), latestLabels = [];
let localFiles = new Map(), cameraControls = null, paletteControls = null;
let options = {mode: 'solid', edges: true, colors: 'surface', scale: 'real', labels: true, grid: true};

function showError(message, retry = false) {
  $('error').hidden = false;
  $('error').querySelector('span').textContent = message;
  $('retry').hidden = !retry;
}
function clearError() { $('error').hidden = true; }
function orderedIds() { return [...selected].sort((a, b) => Number(a) - Number(b)); }
function sizeText(model) {
  const dimensions = model.bounds[0].map((v, i) => model.bounds[1][i] - v);
  return dimensions.map(v => v < .1 ? v.toPrecision(3) : v.toFixed(1)).join(' × ') + '（原坐标单位）';
}
function renderLabels(labels) {
  latestLabels = labels;
  const active = new Set(labels.map(label => String(label.id)));
  for (const [id, el] of labelElements) {
    if (!active.has(id)) { el.remove(); labelElements.delete(id); }
  }
  for (const label of labels) {
    const id = String(label.id);
    let el = labelElements.get(id);
    if (!el) {
      el = document.createElement('button');
      el.className = 'scene-label';
      el.textContent = '#' + id;
      el.setAttribute('aria-label', '单独查看楼栋 ' + id);
      el.onclick = () => selectIds([id]);
      $('model-labels').append(el);
      labelElements.set(id, el);
    }
    el.style.left = `${label.x}px`;
    el.style.top = `${label.y}px`;
    el.hidden = !options.labels || !label.visible;
    const model = cache.get(id);
    el.title = model ? `楼栋 ${id} · ${sizeText(model)} · 点击单独查看` : `楼栋 ${id}`;
  }
}

function filteredModels() {
  const query = $('search').value.trim().replace(/^#/, '').replace(/\.obj$/i, '');
  if (!query) return catalog;
  return catalog.filter(model => model.id.includes(query)).sort((a, b) => (b.id === query) - (a.id === query) || Number(a.id) - Number(b.id));
}
function renderList() {
  const filtered = filteredModels(), pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  page = Math.min(page, pageCount - 1);
  $('filter-count').textContent = `${number(filtered.length)} 栋可选`;
  $('random-selection').disabled = !catalog.length;
  $('page-info').textContent = `${page + 1} / ${pageCount} 页`;
  $('previous-page').disabled = page === 0;
  $('next-page').disabled = page >= pageCount - 1;
  const fragment = document.createDocumentFragment();
  for (const model of filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE)) {
    const row = document.createElement('label');
    row.className = 'model-row' + (selected.has(model.id) ? ' selected' : '');
    const check = document.createElement('input');
    check.type = 'checkbox'; check.checked = selected.has(model.id);
    check.setAttribute('aria-label', `选择楼栋 ${model.id}`);
    check.onchange = () => {
      const next = new Set(selected);
      if (check.checked) next.add(model.id); else next.delete(model.id);
      if (!selectIds([...next])) check.checked = selected.has(model.id);
    };
    const text = document.createElement('span'); text.className = 'model-text';
    const title = document.createElement('strong'); title.textContent = `# ${model.id}`;
    const sub = document.createElement('small');
    sub.textContent = model.triangles !== undefined ? `${number(model.triangles)} 面 · ${(model.bytes / 1024).toFixed(1)} KB` : `${(model.bytes / 1024).toFixed(1)} KB`;
    text.append(title, sub); row.append(check, text);
    if (model.watertight === true) {
      const mark = document.createElement('span'); mark.className = 'mesh-mark'; mark.textContent = '闭合';
      mark.title = '已有提交清单记录为闭合；未在网页中重新检查'; row.append(mark);
    }
    row.title = model.fallback_original ? '此栋为提交清单标注的原结果回退版本' : `查看 ${model.id}.obj`;
    fragment.append(row);
  }
  if (!filtered.length) {
    const empty = document.createElement('p'); empty.className = 'empty-list'; empty.textContent = '没有匹配的编号'; fragment.append(empty);
  }
  $('model-list').replaceChildren(fragment);
}
function renderSelection(syncInput = true) {
  $('selection-count').textContent = `${selected.size} / ${MAX_SELECTED}`;
  $('previous-group').disabled = !selected.size; $('next-group').disabled = !selected.size;
  const fragment = document.createDocumentFragment();
  for (const id of orderedIds()) {
    const chip = document.createElement('span'); chip.className = 'model-chip';
    const focus = document.createElement('button'); focus.textContent = `# ${id}`;
    focus.title = cache.has(id) ? `${sizeText(cache.get(id))} · 点击单独查看` : '单独查看楼栋 ' + id;
    focus.onclick = () => selectIds([id]);
    const remove = document.createElement('button'); remove.className = 'remove-chip'; remove.textContent = '×';
    remove.setAttribute('aria-label', `移除楼栋 ${id}`);
    remove.onclick = () => selectIds([...selected].filter(value => value !== id));
    chip.append(focus, remove); fragment.append(chip);
  }
  if (!selected.size) {
    const hint = document.createElement('span'); hint.className = 'selected-empty'; hint.textContent = '尚未选择楼栋'; fragment.append(hint);
  }
  $('selected-models').replaceChildren(fragment);
  if (syncInput) $('batch-ids').value = orderedIds().join(', ');
}
function selectIds(ids) {
  const unique = [...new Set(ids.map(String))];
  const invalid = unique.filter(id => !catalogById.has(id));
  if (invalid.length) { showError(`找不到楼栋编号：${invalid.slice(0, 8).join('、')}`); return false; }
  if (unique.length > MAX_SELECTED) { showError(`一次最多预览 ${MAX_SELECTED} 栋，当前选择了 ${unique.length} 栋。请缩小编号范围。`); return false; }
  selected = new Set(unique); clearError(); renderSelection(); renderList(); loadSelection(); return true;
}
function parseIds(value) {
  if (!value.trim()) return [];
  const normalized = value.trim().replace(/\s*[-–—~～]\s*/g, '-');
  const tokens = normalized.split(/[\s,，;；、]+/).filter(Boolean);
  const result = new Set();
  for (const token of tokens) {
    const match = token.match(/^#?(\d+)(?:-(\d+))?$/);
    if (!match) throw Error(`无法识别“${token}”。请使用编号或范围，例如 1, 3, 100-105。`);
    const start = Number(match[1]), end = match[2] ? Number(match[2]) : start;
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end) throw Error(`编号范围不正确：${token}`);
    if (end - start + 1 > MAX_SELECTED) throw Error(`一次最多预览 ${MAX_SELECTED} 栋，请缩小编号范围。`);
    for (let id = start; id <= end; id++) result.add(String(id));
    if (result.size > MAX_SELECTED) throw Error(`一次最多预览 ${MAX_SELECTED} 栋。`);
  }
  return [...result];
}
function applyBatch(append) {
  try { const ids = parseIds($('batch-ids').value); selectIds(append ? [...selected, ...ids] : ids); }
  catch (error) { showError(error.message); }
}
async function loadSelection() {
  const version = ++generation;
  controller?.abort(); controller = new AbortController();
  const signal = controller.signal, ids = orderedIds();
  if (!ids.length) {
    currentModels = [];
    viewer?.setModels([]);
    cameraControls?.refresh(); updateHeightLegend();
    renderLabels([]);
    $('loading').hidden = true; $('empty-state').hidden = false; $('screenshot').disabled = true;
    $('scene-stats').textContent = catalog.length ? '未选择楼栋' : '请先点击左侧“选择模型文件夹”';
    return;
  }
  $('loading').hidden = !ids.length;
  $('empty-state').hidden = !!ids.length;
  $('screenshot').disabled = true;
  $('scene-stats').textContent = ids.length ? `正在读取 ${ids.length} 栋模型…` : '未选择楼栋';
  const results = new Map(), failures = []; let next = 0, completed = 0;
  const worker = async () => {
    while (next < ids.length && !signal.aborted) {
      const id = ids[next++];
      try {
        let model = cache.get(id);
        if (!model) {
          const file = localFiles.get(id);
          if (!file) throw Error('本地文件已不可用，请重新选择文件夹');
          const text = await file.text();
          if (signal.aborted || version !== generation) return;
          model = parseOBJ(text, id, file.size);
          if (signal.aborted || version !== generation) return;
          cache.set(id, model);
          if (cache.size > 64) cache.delete(cache.keys().next().value);
        }
        results.set(id, model);
      } catch (error) {
        if (error.name !== 'AbortError') failures.push(`#${id}：${error.message}`);
      }
      completed++;
      if (version === generation) $('loading').querySelector('span').textContent = `正在读取模型 ${completed} / ${ids.length}`;
    }
  };
  await Promise.all(Array.from({length: Math.min(4, ids.length)}, worker));
  if (version !== generation) return;
  const savedView = cameraControls?.preserveView ? cameraControls.capture() : null;
  currentModels = ids.map(id => results.get(id)).filter(Boolean);
  try {
    viewer?.setModels(currentModels);
    if (savedView && currentModels.length) cameraControls.restore(savedView, {checkScene: false});
    cameraControls?.refresh(); updateHeightLegend();
    const triangles = currentModels.reduce((sum, m) => sum + m.faces.length, 0);
    const vertices = currentModels.reduce((sum, m) => sum + m.vertices.length, 0);
    $('scene-stats').textContent = currentModels.length ? `已显示 ${currentModels.length} / ${ids.length} 栋 · ${number(triangles)} 三角面 · ${number(vertices)} 顶点` : '未显示模型';
    $('screenshot').disabled = !currentModels.length || !viewer;
    $('empty-state').hidden = !!currentModels.length;
    if (failures.length) showError('部分模型读取失败。' + failures.join('；'), true);
    renderSelection(false);
  } catch (error) { showError(`模型渲染失败：${error.message}`, true); }
  finally { $('loading').hidden = true; }
}
function updateHeightLegend() {
  const legend = $('height-legend'); if (!legend) return;
  const range = viewer?.getState().colorRange;
  const valid = range && Number.isFinite(range.min) && Number.isFinite(range.max);
  legend.hidden = !(options.colors === 'height' && currentModels.length && valid);
  if (valid) {
    $('height-min').textContent = Number(range.min.toPrecision(6)).toString();
    $('height-max').textContent = Number(range.max.toPrecision(6)).toString();
    legend.querySelector('i').style.background = paletteGradient(options.palette, options.reverse);
    paletteControls?.setDataRange?.(range);
  }
}
function updateOptions() {
  const savedView = cameraControls?.preserveView && $('scale-mode').value !== options.scale ? cameraControls.capture() : null;
  options = {mode: $('display-mode').value, scale: $('scale-mode').value, colors: $('color-mode').value, edges: $('show-edges').checked, labels: $('show-labels').checked, grid: $('show-grid').checked, ...paletteControls?.getOptions()};
  viewer?.setOptions(options);
  if (savedView && currentModels.length) cameraControls.restore(savedView, {checkScene: false});
  paletteControls?.setScalarEnabled(options.colors === 'height');
  cameraControls?.refresh(); updateHeightLegend();
  $('layout-title').textContent = options.scale === 'real' ? '等比例陈列' : '统一展示大小';
  $('layout-note').textContent = options.scale === 'real' ? '独立模型重新排列 · 非实际地理位置' : '各栋独立等比缩放 · 不可比较实际大小';
  $('legend').hidden = options.colors !== 'surface' || options.mode === 'wire';
  renderLabels(latestLabels);
}
function nextGroup(direction) {
  if (!catalog.length || !selected.size) return;
  const count = selected.size, ids = orderedIds();
  let start = direction > 0 ? catalog.findIndex(m => m.id === ids.at(-1)) + 1 : catalog.findIndex(m => m.id === ids[0]) - count;
  start = ((start % catalog.length) + catalog.length) % catalog.length;
  selectIds(Array.from({length: Math.min(count, catalog.length)}, (_, i) => catalog[(start + i) % catalog.length].id));
}
function screenshot() {
  if (!viewer || !currentModels.length) return;
  viewer.render();
  const canvas = $('scene'), result = document.createElement('canvas');
  const header = 80; result.width = canvas.width; result.height = canvas.height + header;
  const ctx = result.getContext('2d');
  ctx.fillStyle = '#f5f8f7'; ctx.fillRect(0, 0, result.width, result.height);
  ctx.drawImage(canvas, 0, header);
  ctx.fillStyle = '#2d4845'; ctx.font = '500 23px sans-serif';
  ctx.fillText('LOD · ' + currentModels.map(model => '#' + model.id).join('  '), 25, 32, result.width - 50);
  ctx.font = '14px sans-serif'; ctx.fillStyle = '#738580';
  ctx.fillText($('layout-title').textContent + ' / ' + $('layout-note').textContent, 25, 58, result.width - 50);
  const ratio = canvas.width / canvas.clientWidth;
  if (options.labels) for (const label of latestLabels) {
    if (!label.visible) continue;
    ctx.font = `${12 * ratio}px sans-serif`; ctx.textAlign = 'center'; ctx.fillStyle = '#3b5b53';
    ctx.fillText('#' + label.id, label.x * ratio, header + (label.y + 13) * ratio);
  }
  const filename = `LOD_${orderedIds().join('-')}_${options.scale}.png`;
  result.toBlob(blob => {
    if (!blob) { showError('无法生成截图，请降低窗口尺寸后重试。'); return; }
    const url = URL.createObjectURL(blob), link = document.createElement('a');
    link.download = filename; link.href = url; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 60000);
  }, 'image/png');
}

$('replace-selection').onclick = () => applyBatch(false);
$('add-selection').onclick = () => applyBatch(true);
$('batch-ids').onkeydown = event => { if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) applyBatch(false); };
$('search').oninput = () => { page = 0; renderList(); };
$('previous-page').onclick = () => { page--; renderList(); $('model-list').scrollTop = 0; };
$('next-page').onclick = () => { page++; renderList(); $('model-list').scrollTop = 0; };
$('clear-selection').onclick = () => selectIds([]);
$('random-selection').onclick = () => {
  const pool = catalog.map(m => m.id);
  for (let i = pool.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [pool[i], pool[j]] = [pool[j], pool[i]]; }
  selectIds(pool.slice(0, 6));
};
$('previous-group').onclick = () => nextGroup(-1);
$('next-group').onclick = () => nextGroup(1);
$('fit-view').onclick = () => viewer?.fit();
$('zoom-in').onclick = () => viewer?.zoomBy(1.2);
$('zoom-out').onclick = () => viewer?.zoomBy(1 / 1.2);
$('screenshot').onclick = screenshot;
$('retry').onclick = () => { clearError(); if (!catalog.length || !viewer) init(); else loadSelection(); };
$('dismiss-error').onclick = clearError;
for (const button of document.querySelectorAll('[data-view]')) button.onclick = () => {
  viewer?.setView(button.dataset.view);
  for (const other of document.querySelectorAll('[data-view]')) { other.classList.toggle('active', other === button); other.setAttribute('aria-pressed', String(other === button)); }
};
for (const id of ['display-mode', 'scale-mode', 'color-mode', 'show-edges', 'show-labels', 'show-grid']) $(id).onchange = updateOptions;
document.addEventListener('keydown', event => {
  if (['INPUT', 'TEXTAREA', 'SELECT', 'BUTTON'].includes(event.target.tagName)) return;
  if (event.key.toLowerCase() === 'f') { event.preventDefault(); viewer?.fit(); }
});

function ensureViewer() {
  if (!viewer) viewer = new MeshViewer($('scene'), {onLabels: renderLabels, onError: message => message ? showError(String(message), true) : clearError()});
  if (!paletteControls && $('palette-controls')) paletteControls = mountPaletteControls({container: $('palette-controls'), getOptions: () => options, onChange: updateOptions});
  if (!cameraControls && $('camera-controls')) cameraControls = mountCameraControls({container: $('camera-controls'), bookmarkContainer: $('bookmark-controls'), getViewers: () => viewer ? [viewer] : [], space: 'lod-arrangement', getScene: () => ({ids: currentModels.map(model => String(model.id)), scale: options.scale})});
  options = {...options, ...paletteControls?.getOptions()};
  viewer.setOptions(options); paletteControls?.setScalarEnabled(options.colors === 'height');
}
function folderReady(fileList) {
  if (!fileList.length) return;
  ++generation; controller?.abort(); cache.clear();
  localFiles = new Map(); catalog = []; catalogById = new Map(); page = 0;
  $('search').value = '';
  $('total-count').textContent = '0 栋模型';
  $('source-path').textContent = '尚未选择可用的 OBJ 目录';
  $('folder-status').textContent = '请选择包含 OBJ 文件的目录';
  selectIds([]);
  const files = [...fileList].filter(file => /\.obj$/i.test(file.name));
  if (!files.length) { showError('这个文件夹中没有 OBJ 文件，请选择包含 .obj 模型的目录。'); return; }
  const mapped = new Map();
  for (const file of files) {
    const id = file.name.replace(/\.obj$/i, '');
    if (mapped.has(id)) { showError(`文件夹包含同名模型 ${file.name}，请直接选择只含一套结果的子文件夹。`); return; }
    mapped.set(id, file);
  }
  try { ensureViewer(); } catch (error) { showError(error.message); return; }
  ++generation; controller?.abort(); cache.clear();
  localFiles = mapped;
  catalog = [...mapped].map(([id, file]) => ({id, bytes: file.size})).sort((a, b) => a.id.localeCompare(b.id, undefined, {numeric: true}));
  catalogById = new Map(catalog.map(model => [model.id, model]));
  page = 0; $('search').value = '';
  const name = files[0].webkitRelativePath.split('/')[0] || '本地文件夹';
  $('source-path').textContent = name + '（浏览器选择的本地文件夹）';
  $('folder-status').textContent = `${number(files.length)} 个 OBJ · 仅按需读取所选楼栋`;
  $('total-count').textContent = `${number(files.length)} 栋模型`;
  selectIds([]);
}
$('choose-folder').onclick = () => $('folder-input').click();
$('folder-input').onchange = event => { folderReady(event.target.files); event.target.value = ''; };

function init() {
  try {
    ensureViewer();
    mountViewerLayout();
    $('total-count').textContent = '尚未选择文件夹';
    $('source-path').textContent = '尚未选择文件夹。关闭或刷新网页后，请手动重新选择。';
    $('folder-status').textContent = '选择含 OBJ 的目录 · 文件仅在本机读取';
    selectIds([]);
  } catch (error) {
    $('scene-stats').textContent = '查看器暂时无法启动';
    $('loading').hidden = true;
    showError(`查看器启动失败：${error.message}。请使用支持 WebGL 的浏览器。`, true);
    $('empty-state').hidden = false;
  }
}
init();

})();
