// Generated by build.py; edit source files and rebuild.
(() => {
'use strict';

// Source: renderer.js
/** Local, dependency-free mesh renderer. Building placement is synthetic; geometry and scale are preserved. */
const DEG = Math.PI / 180;
const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const clamp = (value, low, high) => Math.max(low, Math.min(high, value));
const PALETTE = [[.39, .57, .67], [.64, .61, .46], [.50, .63, .58], [.62, .52, .64], [.67, .53, .43], [.45, .61, .72], [.65, .61, .69], [.55, .66, .46]];
const VERTEX_SHADER = `
precision highp float;
attribute vec3 position;
attribute vec3 normal;
attribute vec3 buildingColor;
uniform mat4 matrix;
uniform int kind;
uniform int colorByBuilding;
varying vec4 color;
void main() {
  gl_Position = matrix * vec4(position, 1.0);
  if (kind == 0) {
    vec3 base = abs(normal.z) > .22 ? vec3(.46, .59, .67) : vec3(.91, .89, .84);
    if (colorByBuilding == 1) base = buildingColor * (abs(normal.z) > .22 ? .86 : 1.13);
    float light = .75 + .25 * abs(dot(normal, normalize(vec3(-.5, -.7, 1.1))));
    color = vec4(base * light, 1.0);
  } else if (kind == 2) {
    color = vec4(.67, .71, .74, .24);
  } else if (kind == 3) {
    color = vec4(.23, .36, .43, .64);
  } else {
    color = vec4(.23, .31, .36, .65);
  }
}`;
const FRAGMENT_SHADER = `precision mediump float; varying vec4 color; void main() { gl_FragColor = color; }`;

class MeshViewer {
  constructor(canvas, { onLabels = () => {}, onError = () => {} } = {}) {
    this.canvas = canvas;
    this.onLabels = onLabels;
    this.onError = onError;
    this.options = { mode: 'solid', edges: true, colors: 'surface', grid: true, labels: true, scale: 'real' };
    this.camera = { elevation: 38, azimuth: -55, zoom: 1, pan: [0, 0] };
    this.baseHeight = 30;
    this.sceneBounds = [[-5, -5, 0], [5, 5, 10]];
    this.target = [0, 0, 5];
    this.models = [];
    this.labelAnchors = [];
    this.buffers = {};
    this.triangleCount = 0;
    this.disposed = false;
    this.contextLost = false;
    this.frame = null;
    this.listeners = [];
    try {
      this.gl = canvas.getContext('webgl', { antialias: true, alpha: false, preserveDrawingBuffer: true });
      if (!this.gl) throw new Error('此浏览器无法启用 WebGL，请检查浏览器的硬件加速设置。');
      this.initGL();
    } catch (error) {
      this.onError(error.message);
      throw error;
    }
    this.installEvents();
    this.resizeObserver = new ResizeObserver(() => this.requestRender());
    this.resizeObserver.observe(canvas);
    this.render();
  }

  initGL() {
    const gl = this.gl;
    const compile = (type, source) => {
      const shader = gl.createShader(type);
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        const message = gl.getShaderInfoLog(shader);
        gl.deleteShader(shader);
        throw new Error(`WebGL 着色器编译失败：${message}`);
      }
      return shader;
    };
    const vertex = compile(gl.VERTEX_SHADER, VERTEX_SHADER);
    const fragment = compile(gl.FRAGMENT_SHADER, FRAGMENT_SHADER);
    const program = gl.createProgram();
    gl.attachShader(program, vertex);
    gl.attachShader(program, fragment);
    gl.linkProgram(program);
    gl.deleteShader(vertex);
    gl.deleteShader(fragment);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      const message = gl.getProgramInfoLog(program);
      gl.deleteProgram(program);
      throw new Error(`WebGL 程序链接失败：${message}`);
    }
    this.program = program;
    this.locations = {
      position: gl.getAttribLocation(program, 'position'),
      normal: gl.getAttribLocation(program, 'normal'),
      buildingColor: gl.getAttribLocation(program, 'buildingColor'),
      matrix: gl.getUniformLocation(program, 'matrix'),
      kind: gl.getUniformLocation(program, 'kind'),
      colorByBuilding: gl.getUniformLocation(program, 'colorByBuilding'),
    };
  }

  installEvents() {
    const listen = (name, fn, options) => {
      this.canvas.addEventListener(name, fn, options);
      this.listeners.push([name, fn, options]);
    };
    this.canvas.style.touchAction = 'none';
    listen('contextmenu', event => event.preventDefault());
    listen('pointerdown', event => {
      if (event.button !== 0 && event.button !== 2 && event.button !== 1) return;
      event.preventDefault();
      this.canvas.setPointerCapture(event.pointerId);
      this.drag = { pointerId: event.pointerId, x: event.clientX, y: event.clientY,
        pan: event.button !== 0 || event.shiftKey };
      this.canvas.style.cursor = 'grabbing';
    });
    listen('pointermove', event => {
      if (!this.drag || this.drag.pointerId !== event.pointerId) return;
      const dx = event.clientX - this.drag.x, dy = event.clientY - this.drag.y;
      this.drag.x = event.clientX;
      this.drag.y = event.clientY;
      if (this.drag.pan || event.shiftKey) {
        const pixelSize = this.baseHeight / this.camera.zoom / Math.max(1, this.canvas.clientHeight);
        this.camera.pan[0] -= dx * pixelSize;
        this.camera.pan[1] += dy * pixelSize;
      } else {
        this.camera.azimuth = (this.camera.azimuth - dx * .35) % 360;
        this.camera.elevation = clamp(this.camera.elevation + dy * .3, 0, 90);
      }
      this.requestRender();
    });
    const finish = event => {
      if (this.drag?.pointerId !== event.pointerId) return;
      this.drag = null;
      this.canvas.style.cursor = 'grab';
      if (this.canvas.hasPointerCapture(event.pointerId)) this.canvas.releasePointerCapture(event.pointerId);
    };
    listen('pointerup', finish);
    listen('pointercancel', finish);
    listen('lostpointercapture', finish);
    listen('wheel', event => {
      event.preventDefault();
      const delta = event.deltaY * (event.deltaMode === 1 ? 16 : event.deltaMode === 2 ? this.canvas.clientHeight : 1);
      this.zoomBy(Math.exp(-clamp(delta, -500, 500) * .0015));
    }, { passive: false });
    listen('webglcontextlost', event => {
      event.preventDefault();
      this.contextLost = true;
      this.onError('WebGL 显示上下文暂时丢失，正在等待浏览器恢复。');
    });
    listen('webglcontextrestored', () => {
      this.contextLost = false;
      try {
        this.buffers = {};
        this.initGL();
        this.setModels(this.models);
        this.onError('');
      } catch (error) { this.onError(error.message); }
    });
  }

  makeBuffer(values) {
    const gl = this.gl, buffer = gl.createBuffer();
    if (!buffer) throw new Error('无法分配 WebGL 缓冲区，请减少同时查看的楼栋数量。');
    gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(values), gl.STATIC_DRAW);
    if (gl.getError() === gl.OUT_OF_MEMORY) {
      gl.deleteBuffer(buffer);
      throw new Error('显存不足，请减少同时查看的楼栋数量。');
    }
    return { buffer, count: values.length / 9 };
  }

  setModels(models) {
    if (!Array.isArray(models)) throw new TypeError('setModels 需要模型数组。');
    const prepared = models.map(model => {
      if (!model.vertices?.length || !Array.isArray(model.faces)) throw new Error(`楼栋 ${model.id} 缺少有效网格。`);
      const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
      for (const point of model.vertices) {
        if (point.length < 3 || !point.slice(0, 3).every(Number.isFinite)) throw new Error(`楼栋 ${model.id} 包含无效坐标。`);
        for (let i = 0; i < 3; i++) { min[i] = Math.min(min[i], point[i]); max[i] = Math.max(max[i], point[i]); }
      }
      const extent = Math.max(...max.map((value, i) => value - min[i]));
      const scale = this.options.scale === 'normalized' && extent > 0 ? 30 / extent : 1;
      return { model, min, max, scale, width: (max[0] - min[0]) * scale, depth: (max[1] - min[1]) * scale };
    });
    const columns = Math.ceil(Math.sqrt(prepared.length)), rows = Math.ceil(prepared.length / (columns || 1));
    const widths = Array(columns).fill(0), depths = Array(rows).fill(0);
    for (let i = 0; i < prepared.length; i++) {
      widths[i % columns] = Math.max(widths[i % columns], prepared[i].width);
      depths[Math.floor(i / columns)] = Math.max(depths[Math.floor(i / columns)], prepared[i].depth);
    }
    const typical = prepared.map(item => Math.max(item.width, item.depth)).sort((a, b) => a - b);
    const gap = Math.max(2, (typical[Math.floor(typical.length / 2)] || 10) * .35);
    const totalWidth = widths.reduce((sum, value) => sum + value, 0) + Math.max(0, columns - 1) * gap;
    const totalDepth = depths.reduce((sum, value) => sum + value, 0) + Math.max(0, rows - 1) * gap;
    const centers = values => {
      let offset = 0;
      return values.map(value => { const center = offset + value / 2; offset += value + gap; return center; });
    };
    const xCenters = centers(widths), yCenters = centers(depths);
    const triangles = [], featureEdges = [], allEdges = [], labels = [];
    let maxHeight = 0;
    const vertexOut = (array, position, normal, color) => array.push(...position, ...normal, ...color);
    const featureCosine = Math.cos(10 * DEG);
    for (let modelIndex = 0; modelIndex < prepared.length; modelIndex++) {
      const { model, min, max, scale } = prepared[modelIndex];
      const cx = xCenters[modelIndex % columns] - totalWidth / 2;
      const cy = totalDepth / 2 - yCenters[Math.floor(modelIndex / columns)];
      const vertices = model.vertices.map(v => [(v[0] - (min[0] + max[0]) / 2) * scale + cx, (v[1] - (min[1] + max[1]) / 2) * scale + cy, (v[2] - min[2]) * scale]);
      const height = (max[2] - min[2]) * scale;
      maxHeight = Math.max(maxHeight, height);
      labels.push({ id: model.id, bounds: [[cx - prepared[modelIndex].width / 2, cy - prepared[modelIndex].depth / 2, 0],
        [cx + prepared[modelIndex].width / 2, cy + prepared[modelIndex].depth / 2, height]] });
      let hash = 0;
      for (const char of String(model.id)) hash = ((hash * 31) + char.charCodeAt(0)) >>> 0;
      const color = PALETTE[hash % PALETTE.length];
      // Exact-coordinate welding also handles OBJ files that duplicate vertices at material/normal seams.
      const unique = new Map();
      const welded = vertices.map((v, index) => { const key = v.join(','); if (!unique.has(key)) unique.set(key, index); return unique.get(key); });
      const edges = new Map();
      for (const face of model.faces) {
        if (face.length !== 3 || !face.every(index => Number.isInteger(index) && index >= 0 && index < vertices.length)) {
          throw new Error(`楼栋 ${model.id} 包含无效三角面。`);
        }
        const [a, b, c] = face.map(index => vertices[index]);
        const ab = b.map((value, i) => value - a[i]), ac = c.map((value, i) => value - a[i]);
        const normal = [ab[1] * ac[2] - ab[2] * ac[1], ab[2] * ac[0] - ab[0] * ac[2], ab[0] * ac[1] - ab[1] * ac[0]];
        const length = Math.hypot(...normal);
        if (length < 1e-12) continue;
        for (let i = 0; i < 3; i++) normal[i] /= length;
        for (const point of [a, b, c]) vertexOut(triangles, point, normal, color);
        for (let i = 0; i < 3; i++) {
          const ai = welded[face[i]], bi = welded[face[(i + 1) % 3]];
          const key = ai < bi ? `${ai}:${bi}` : `${bi}:${ai}`;
          if (!edges.has(key)) edges.set(key, { a: vertices[ai], b: vertices[bi], normals: [] });
          edges.get(key).normals.push(normal);
        }
      }
      for (const edge of edges.values()) {
        vertexOut(allEdges, edge.a, [0, 0, 1], color);
        vertexOut(allEdges, edge.b, [0, 0, 1], color);
        const normals = edge.normals;
        const feature = normals.length !== 2 || Math.abs(dot(normals[0], normals[1])) < featureCosine;
        if (feature) {
          vertexOut(featureEdges, edge.a, [0, 0, 1], color);
          vertexOut(featureEdges, edge.b, [0, 0, 1], color);
        }
      }
    }
    const nextBuffers = {};
    try {
      nextBuffers.triangles = this.makeBuffer(triangles);
      nextBuffers.featureEdges = this.makeBuffer(featureEdges);
      nextBuffers.allEdges = this.makeBuffer(allEdges);
      const grid = [], span = Math.max(totalWidth, totalDepth, 10) * .7 + gap;
      const roughStep = span / 15, power = Math.pow(10, Math.floor(Math.log10(roughStep)));
      const unit = roughStep / power;
      const step = (unit <= 1 ? 1 : unit <= 2 ? 2 : unit <= 5 ? 5 : 10) * power;
      const gridExtent = Math.ceil(span / step) * step;
      const z = -Math.max(.005, maxHeight * .0001);
      for (let k = -Math.floor(gridExtent / step); k <= Math.floor(gridExtent / step); k++) {
        for (const point of [[k * step, -gridExtent, z], [k * step, gridExtent, z], [-gridExtent, k * step, z], [gridExtent, k * step, z]]) vertexOut(grid, point, [0, 0, 1], [1, 1, 1]);
      }
      nextBuffers.grid = this.makeBuffer(grid);
    } catch (error) {
      for (const item of Object.values(nextBuffers)) this.gl.deleteBuffer(item.buffer);
      this.onError(error.message);
      throw error;
    }
    for (const item of Object.values(this.buffers)) this.gl.deleteBuffer(item.buffer);
    this.buffers = nextBuffers;
    this.models = models;
    this.labelAnchors = labels;
    this.triangleCount = triangles.length / 27;
    this.sceneBounds = prepared.length ? [[-totalWidth / 2, -totalDepth / 2, 0], [totalWidth / 2, totalDepth / 2, maxHeight]] : [[-5, -5, 0], [5, 5, 10]];
    this.target = prepared.length ? [0, 0, maxHeight / 2] : [0, 0, 5];
    this.fit();
  }

  setOptions(options) {
    const next = { ...this.options, ...options };
    if (!['solid', 'wire', 'solid-wire'].includes(next.mode)) throw new Error(`不支持的显示模式：${next.mode}`);
    if (!['surface', 'building'].includes(next.colors)) throw new Error(`不支持的配色模式：${next.colors}`);
    if (!['real', 'normalized'].includes(next.scale)) throw new Error(`不支持的比例模式：${next.scale}`);
    const rebuild = next.scale !== this.options.scale;
    this.options = next;
    if (rebuild) this.setModels(this.models);
    else this.render();
  }

  setView(view) {
    const views = { iso: [38, -55], top: [90, -90], front: [0, -90] };
    if (!views[view]) throw new Error(`不支持的视角：${view}`);
    [this.camera.elevation, this.camera.azimuth] = views[view];
    this.fit();
  }

  basis() {
    const e = this.camera.elevation * DEG, a = this.camera.azimuth * DEG;
    return [[-Math.sin(a), Math.cos(a), 0], [-Math.cos(a) * Math.sin(e), -Math.sin(a) * Math.sin(e), Math.cos(e)], [Math.cos(a) * Math.cos(e), Math.sin(a) * Math.cos(e), Math.sin(e)]];
  }

  fit() {
    const [right, up] = this.basis(), [min, max] = this.sceneBounds;
    let xMin = Infinity, xMax = -Infinity, yMin = Infinity, yMax = -Infinity;
    for (const x of [min[0], max[0]]) for (const y of [min[1], max[1]]) for (const z of [min[2], max[2]]) {
      const point = [x, y, z], projectedX = dot(point, right), projectedY = dot(point, up);
      xMin = Math.min(xMin, projectedX); xMax = Math.max(xMax, projectedX);
      yMin = Math.min(yMin, projectedY); yMax = Math.max(yMax, projectedY);
    }
    const aspect = Math.max(1, this.canvas.clientWidth) / Math.max(1, this.canvas.clientHeight);
    this.baseHeight = Math.max(2, yMax - yMin, (xMax - xMin) / aspect) * 1.3;
    this.camera.zoom = 1;
    this.camera.pan = [0, 0];
    this.render();
  }

  zoomBy(factor) {
    if (!Number.isFinite(factor) || factor <= 0) return;
    this.camera.zoom = clamp(this.camera.zoom * factor, .15, 30);
    this.render();
  }

  matrix() {
    const [r, u, t] = this.basis();
    const aspect = this.canvas.width / Math.max(1, this.canvas.height);
    const height = this.baseHeight / this.camera.zoom, width = height * aspect;
    const cx = dot(this.target, r) + this.camera.pan[0], cy = dot(this.target, u) + this.camera.pan[1];
    const depth = Math.max(10, Math.hypot(...this.sceneBounds[1].map((v, i) => v - this.sceneBounds[0][i]))) * 4;
    return new Float32Array([2 * r[0] / width, 2 * u[0] / height, -t[0] / depth, 0,
      2 * r[1] / width, 2 * u[1] / height, -t[1] / depth, 0,
      2 * r[2] / width, 2 * u[2] / height, -t[2] / depth, 0,
      -2 * cx / width, -2 * cy / height, dot(this.target, t) / depth, 1]);
  }

  requestRender() {
    if (this.frame !== null || this.disposed) return;
    this.frame = requestAnimationFrame(() => { this.frame = null; this.render(); });
  }

  render() {
    if (this.disposed || this.contextLost) return;
    if (this.frame !== null) { cancelAnimationFrame(this.frame); this.frame = null; }
    const canvas = this.canvas, gl = this.gl, rect = canvas.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const width = Math.max(1, Math.round(rect.width * dpr)), height = Math.max(1, Math.round(rect.height * dpr));
    if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; }
    const matrix = this.matrix(), loc = this.locations;
    gl.viewport(0, 0, width, height);
    gl.clearColor(.951, .960, .965, 1);
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    gl.useProgram(this.program);
    gl.uniformMatrix4fv(loc.matrix, false, matrix);
    gl.uniform1i(loc.colorByBuilding, this.options.colors === 'building' ? 1 : 0);
    for (const location of [loc.position, loc.normal, loc.buildingColor]) gl.enableVertexAttribArray(location);
    gl.disable(gl.CULL_FACE); // Input meshes may use mixed winding; both sides must remain visible.
    gl.enable(gl.DEPTH_TEST);
    gl.depthFunc(gl.LEQUAL);
    gl.enable(gl.BLEND);
    gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
    const draw = (buffer, kind, primitive) => {
      if (!buffer?.count) return;
      gl.bindBuffer(gl.ARRAY_BUFFER, buffer.buffer);
      gl.vertexAttribPointer(loc.position, 3, gl.FLOAT, false, 36, 0);
      gl.vertexAttribPointer(loc.normal, 3, gl.FLOAT, false, 36, 12);
      gl.vertexAttribPointer(loc.buildingColor, 3, gl.FLOAT, false, 36, 24);
      gl.uniform1i(loc.kind, kind);
      gl.drawArrays(primitive, 0, buffer.count);
    };
    if (this.options.grid && this.models.length) draw(this.buffers.grid, 2, gl.LINES);
    if (this.options.mode !== 'wire') {
      gl.enable(gl.POLYGON_OFFSET_FILL);
      gl.polygonOffset(1, 1);
      draw(this.buffers.triangles, 0, gl.TRIANGLES);
      gl.disable(gl.POLYGON_OFFSET_FILL);
    }
    if (this.options.mode === 'wire' || this.options.mode === 'solid-wire') draw(this.buffers.allEdges, 3, gl.LINES);
    else if (this.options.edges) draw(this.buffers.featureEdges, 1, gl.LINES);
    this.onLabels(this.options.labels ? this.labelAnchors.map(({ id, bounds: [min, max] }) => {
      let xMin = Infinity, xMax = -Infinity, yMin = Infinity;
      for (const px of [min[0], max[0]]) for (const py of [min[1], max[1]]) for (const pz of [min[2], max[2]]) {
        const x = matrix[0] * px + matrix[4] * py + matrix[8] * pz + matrix[12];
        const y = matrix[1] * px + matrix[5] * py + matrix[9] * pz + matrix[13];
        xMin = Math.min(xMin, x); xMax = Math.max(xMax, x); yMin = Math.min(yMin, y);
      }
      const x = (xMin + xMax) / 2;
      const screenY = (1 - yMin) * rect.height / 2 + 8;
      return { id, x: (x + 1) * rect.width / 2, y: screenY,
        visible: x > -.99 && x < .99 && screenY >= 0 && screenY < rect.height - 24 };
    }) : []);
  }

  getState() {
    return { buildingCount: this.models.length, triangleCount: this.triangleCount,
      featureEdgeCount: (this.buffers.featureEdges?.count || 0) / 2,
      allEdgeCount: (this.buffers.allEdges?.count || 0) / 2,
      syntheticArrangement: true, camera: { ...this.camera, pan: [...this.camera.pan], baseHeight: this.baseHeight },
      options: { ...this.options }, bounds: this.sceneBounds.map(point => [...point]) };
  }

  destroy() {
    this.disposed = true;
    if (this.frame !== null) cancelAnimationFrame(this.frame);
    this.resizeObserver.disconnect();
    for (const [name, fn, options] of this.listeners) this.canvas.removeEventListener(name, fn, options);
    for (const item of Object.values(this.buffers)) this.gl.deleteBuffer(item.buffer);
    this.gl.deleteProgram(this.program);
    this.onLabels([]);
  }
}


// Source: obj-parser.js
/** Parse triangular OBJ geometry without altering source coordinates. */
function parseOBJ(text, id, bytes = 0) {
  const vertices = [], faces = [];
  const bounds = [[Infinity, Infinity, Infinity], [-Infinity, -Infinity, -Infinity]];
  let lineNumber = 0;
  for (const line of text.split(/\r?\n/)) {
    lineNumber++;
    const tokens = line.split('#')[0].trim().split(/\s+/);
    if (tokens[0] === 'v') {
      const vertex = tokens.slice(1, 4).map(Number);
      if (vertex.length !== 3 || vertex.some(v => !Number.isFinite(v))) throw Error(`第 ${lineNumber} 行顶点坐标无效`);
      vertices.push(vertex);
      vertex.forEach((value, axis) => { bounds[0][axis] = Math.min(bounds[0][axis], value); bounds[1][axis] = Math.max(bounds[1][axis], value); });
    } else if (tokens[0] === 'f') {
      if (tokens.length !== 4) throw Error(`第 ${lineNumber} 行不是三角面，当前查看器需要三角化 OBJ`);
      faces.push(tokens.slice(1).map(token => {
        const index = Number(token.split('/')[0]);
        if (!Number.isSafeInteger(index) || index === 0) throw Error(`第 ${lineNumber} 行面索引无效`);
        const resolved = index > 0 ? index - 1 : vertices.length + index;
        if (resolved < 0) throw Error(`第 ${lineNumber} 行面索引越界`);
        return resolved;
      }));
    }
  }
  if (!vertices.length || !faces.length) throw Error('OBJ 中没有可显示的顶点和三角面');
  if (faces.some(face => face.some(index => index >= vertices.length))) throw Error('OBJ 面索引超出顶点范围');
  return {id, vertices, faces, bounds, stats: {vertices: vertices.length, triangles: faces.length, bytes}};
}


// Source: app.js


const $ = (id) => document.getElementById(id);
const MAX_SELECTED = 24, PAGE_SIZE = 50;
const number = (value) => Number(value).toLocaleString('zh-CN');
let catalog = [], catalogById = new Map(), selected = new Set(), page = 0;
let cache = new Map(), currentModels = [], viewer, generation = 0, controller;
let labelElements = new Map(), latestLabels = [];
let localFiles = new Map();
let options = {mode: 'solid', edges: true, colors: 'surface', scale: 'real', labels: true, grid: true};

function showError(message, retry = false) {
  $('error').hidden = false;
  $('error').querySelector('span').textContent = message;
  $('retry').hidden = !retry;
}
function clearError() { $('error').hidden = true; }
function orderedIds() { return [...selected].sort((a, b) => Number(a) - Number(b)); }
function sizeText(model) {
  const dimensions = model.bounds[0].map((v, i) => model.bounds[1][i] - v);
  return dimensions.map(v => v < .1 ? v.toPrecision(3) : v.toFixed(1)).join(' × ') + '（原坐标单位）';
}
function renderLabels(labels) {
  latestLabels = labels;
  const active = new Set(labels.map(label => String(label.id)));
  for (const [id, el] of labelElements) {
    if (!active.has(id)) { el.remove(); labelElements.delete(id); }
  }
  for (const label of labels) {
    const id = String(label.id);
    let el = labelElements.get(id);
    if (!el) {
      el = document.createElement('button');
      el.className = 'scene-label';
      el.textContent = '#' + id;
      el.setAttribute('aria-label', '单独查看楼栋 ' + id);
      el.onclick = () => selectIds([id]);
      $('model-labels').append(el);
      labelElements.set(id, el);
    }
    el.style.left = `${label.x}px`;
    el.style.top = `${label.y}px`;
    el.hidden = !options.labels || !label.visible;
    const model = cache.get(id);
    el.title = model ? `楼栋 ${id} · ${sizeText(model)} · 点击单独查看` : `楼栋 ${id}`;
  }
}

function filteredModels() {
  const query = $('search').value.trim().replace(/^#/, '').replace(/\.obj$/i, '');
  if (!query) return catalog;
  return catalog.filter(model => model.id.includes(query)).sort((a, b) => (b.id === query) - (a.id === query) || Number(a.id) - Number(b.id));
}
function renderList() {
  const filtered = filteredModels(), pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  page = Math.min(page, pageCount - 1);
  $('filter-count').textContent = `${number(filtered.length)} 栋可选`;
  $('random-selection').disabled = !catalog.length;
  $('page-info').textContent = `${page + 1} / ${pageCount} 页`;
  $('previous-page').disabled = page === 0;
  $('next-page').disabled = page >= pageCount - 1;
  const fragment = document.createDocumentFragment();
  for (const model of filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE)) {
    const row = document.createElement('label');
    row.className = 'model-row' + (selected.has(model.id) ? ' selected' : '');
    const check = document.createElement('input');
    check.type = 'checkbox'; check.checked = selected.has(model.id);
    check.setAttribute('aria-label', `选择楼栋 ${model.id}`);
    check.onchange = () => {
      const next = new Set(selected);
      if (check.checked) next.add(model.id); else next.delete(model.id);
      if (!selectIds([...next])) check.checked = selected.has(model.id);
    };
    const text = document.createElement('span'); text.className = 'model-text';
    const title = document.createElement('strong'); title.textContent = `# ${model.id}`;
    const sub = document.createElement('small');
    sub.textContent = model.triangles !== undefined ? `${number(model.triangles)} 面 · ${(model.bytes / 1024).toFixed(1)} KB` : `${(model.bytes / 1024).toFixed(1)} KB`;
    text.append(title, sub); row.append(check, text);
    if (model.watertight === true) {
      const mark = document.createElement('span'); mark.className = 'mesh-mark'; mark.textContent = '闭合';
      mark.title = '已有提交清单记录为闭合；未在网页中重新检查'; row.append(mark);
    }
    row.title = model.fallback_original ? '此栋为提交清单标注的原结果回退版本' : `查看 ${model.id}.obj`;
    fragment.append(row);
  }
  if (!filtered.length) {
    const empty = document.createElement('p'); empty.className = 'empty-list'; empty.textContent = '没有匹配的编号'; fragment.append(empty);
  }
  $('model-list').replaceChildren(fragment);
}
function renderSelection(syncInput = true) {
  $('selection-count').textContent = `${selected.size} / ${MAX_SELECTED}`;
  $('previous-group').disabled = !selected.size; $('next-group').disabled = !selected.size;
  const fragment = document.createDocumentFragment();
  for (const id of orderedIds()) {
    const chip = document.createElement('span'); chip.className = 'model-chip';
    const focus = document.createElement('button'); focus.textContent = `# ${id}`;
    focus.title = cache.has(id) ? `${sizeText(cache.get(id))} · 点击单独查看` : '单独查看楼栋 ' + id;
    focus.onclick = () => selectIds([id]);
    const remove = document.createElement('button'); remove.className = 'remove-chip'; remove.textContent = '×';
    remove.setAttribute('aria-label', `移除楼栋 ${id}`);
    remove.onclick = () => selectIds([...selected].filter(value => value !== id));
    chip.append(focus, remove); fragment.append(chip);
  }
  if (!selected.size) {
    const hint = document.createElement('span'); hint.className = 'selected-empty'; hint.textContent = '尚未选择楼栋'; fragment.append(hint);
  }
  $('selected-models').replaceChildren(fragment);
  if (syncInput) $('batch-ids').value = orderedIds().join(', ');
}
function selectIds(ids) {
  const unique = [...new Set(ids.map(String))];
  const invalid = unique.filter(id => !catalogById.has(id));
  if (invalid.length) { showError(`找不到楼栋编号：${invalid.slice(0, 8).join('、')}`); return false; }
  if (unique.length > MAX_SELECTED) { showError(`一次最多预览 ${MAX_SELECTED} 栋，当前选择了 ${unique.length} 栋。请缩小编号范围。`); return false; }
  selected = new Set(unique); clearError(); renderSelection(); renderList(); loadSelection(); return true;
}
function parseIds(value) {
  if (!value.trim()) return [];
  const normalized = value.trim().replace(/\s*[-–—~～]\s*/g, '-');
  const tokens = normalized.split(/[\s,，;；、]+/).filter(Boolean);
  const result = new Set();
  for (const token of tokens) {
    const match = token.match(/^#?(\d+)(?:-(\d+))?$/);
    if (!match) throw Error(`无法识别“${token}”。请使用编号或范围，例如 1, 3, 100-105。`);
    const start = Number(match[1]), end = match[2] ? Number(match[2]) : start;
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start > end) throw Error(`编号范围不正确：${token}`);
    if (end - start + 1 > MAX_SELECTED) throw Error(`一次最多预览 ${MAX_SELECTED} 栋，请缩小编号范围。`);
    for (let id = start; id <= end; id++) result.add(String(id));
    if (result.size > MAX_SELECTED) throw Error(`一次最多预览 ${MAX_SELECTED} 栋。`);
  }
  return [...result];
}
function applyBatch(append) {
  try { const ids = parseIds($('batch-ids').value); selectIds(append ? [...selected, ...ids] : ids); }
  catch (error) { showError(error.message); }
}
async function loadSelection() {
  const version = ++generation;
  controller?.abort(); controller = new AbortController();
  const signal = controller.signal, ids = orderedIds();
  if (!ids.length) {
    currentModels = [];
    viewer?.setModels([]);
    renderLabels([]);
    $('loading').hidden = true; $('empty-state').hidden = false; $('screenshot').disabled = true;
    $('scene-stats').textContent = catalog.length ? '未选择楼栋' : '请先点击左侧“选择模型文件夹”';
    return;
  }
  $('loading').hidden = !ids.length;
  $('empty-state').hidden = !!ids.length;
  $('screenshot').disabled = true;
  $('scene-stats').textContent = ids.length ? `正在读取 ${ids.length} 栋模型…` : '未选择楼栋';
  const results = new Map(), failures = []; let next = 0, completed = 0;
  const worker = async () => {
    while (next < ids.length && !signal.aborted) {
      const id = ids[next++];
      try {
        let model = cache.get(id);
        if (!model) {
          const file = localFiles.get(id);
          if (!file) throw Error('本地文件已不可用，请重新选择文件夹');
          const text = await file.text();
          if (signal.aborted || version !== generation) return;
          model = parseOBJ(text, id, file.size);
          if (signal.aborted || version !== generation) return;
          cache.set(id, model);
          if (cache.size > 64) cache.delete(cache.keys().next().value);
        }
        results.set(id, model);
      } catch (error) {
        if (error.name !== 'AbortError') failures.push(`#${id}：${error.message}`);
      }
      completed++;
      if (version === generation) $('loading').querySelector('span').textContent = `正在读取模型 ${completed} / ${ids.length}`;
    }
  };
  await Promise.all(Array.from({length: Math.min(4, ids.length)}, worker));
  if (version !== generation) return;
  currentModels = ids.map(id => results.get(id)).filter(Boolean);
  try {
    viewer?.setModels(currentModels);
    const triangles = currentModels.reduce((sum, m) => sum + m.faces.length, 0);
    const vertices = currentModels.reduce((sum, m) => sum + m.vertices.length, 0);
    $('scene-stats').textContent = currentModels.length ? `已显示 ${currentModels.length} / ${ids.length} 栋 · ${number(triangles)} 三角面 · ${number(vertices)} 顶点` : '未显示模型';
    $('screenshot').disabled = !currentModels.length || !viewer;
    $('empty-state').hidden = !!currentModels.length;
    if (failures.length) showError('部分模型读取失败。' + failures.join('；'), true);
    renderSelection(false);
  } catch (error) { showError(`模型渲染失败：${error.message}`, true); }
  finally { $('loading').hidden = true; }
}
function updateOptions() {
  options = {mode: $('display-mode').value, scale: $('scale-mode').value, colors: $('color-mode').value, edges: $('show-edges').checked, labels: $('show-labels').checked, grid: $('show-grid').checked};
  viewer?.setOptions(options);
  $('layout-title').textContent = options.scale === 'real' ? '等比例陈列' : '统一展示大小';
  $('layout-note').textContent = options.scale === 'real' ? '独立模型重新排列 · 非实际地理位置' : '各栋独立等比缩放 · 不可比较实际大小';
  $('legend').hidden = options.colors !== 'surface' || options.mode === 'wire';
  renderLabels(latestLabels);
}
function nextGroup(direction) {
  if (!catalog.length || !selected.size) return;
  const count = selected.size, ids = orderedIds();
  let start = direction > 0 ? catalog.findIndex(m => m.id === ids.at(-1)) + 1 : catalog.findIndex(m => m.id === ids[0]) - count;
  start = ((start % catalog.length) + catalog.length) % catalog.length;
  selectIds(Array.from({length: Math.min(count, catalog.length)}, (_, i) => catalog[(start + i) % catalog.length].id));
}
function screenshot() {
  if (!viewer || !currentModels.length) return;
  viewer.render();
  const canvas = $('scene'), result = document.createElement('canvas');
  const header = 80; result.width = canvas.width; result.height = canvas.height + header;
  const ctx = result.getContext('2d');
  ctx.fillStyle = '#f5f8f7'; ctx.fillRect(0, 0, result.width, result.height);
  ctx.drawImage(canvas, 0, header);
  ctx.fillStyle = '#2d4845'; ctx.font = '500 23px sans-serif';
  ctx.fillText('LOD · ' + currentModels.map(model => '#' + model.id).join('  '), 25, 32, result.width - 50);
  ctx.font = '14px sans-serif'; ctx.fillStyle = '#738580';
  ctx.fillText($('layout-title').textContent + ' / ' + $('layout-note').textContent, 25, 58, result.width - 50);
  const ratio = canvas.width / canvas.clientWidth;
  if (options.labels) for (const label of latestLabels) {
    if (!label.visible) continue;
    ctx.font = `${12 * ratio}px sans-serif`; ctx.textAlign = 'center'; ctx.fillStyle = '#3b5b53';
    ctx.fillText('#' + label.id, label.x * ratio, header + (label.y + 13) * ratio);
  }
  const link = document.createElement('a');
  link.download = `LOD_${orderedIds().join('-')}_${options.scale}.png`;
  link.href = result.toDataURL('image/png'); link.click();
}

$('replace-selection').onclick = () => applyBatch(false);
$('add-selection').onclick = () => applyBatch(true);
$('batch-ids').onkeydown = event => { if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) applyBatch(false); };
$('search').oninput = () => { page = 0; renderList(); };
$('previous-page').onclick = () => { page--; renderList(); $('model-list').scrollTop = 0; };
$('next-page').onclick = () => { page++; renderList(); $('model-list').scrollTop = 0; };
$('clear-selection').onclick = () => selectIds([]);
$('random-selection').onclick = () => {
  const pool = catalog.map(m => m.id);
  for (let i = pool.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [pool[i], pool[j]] = [pool[j], pool[i]]; }
  selectIds(pool.slice(0, 6));
};
$('previous-group').onclick = () => nextGroup(-1);
$('next-group').onclick = () => nextGroup(1);
$('fit-view').onclick = () => viewer?.fit();
$('zoom-in').onclick = () => viewer?.zoomBy(1.2);
$('zoom-out').onclick = () => viewer?.zoomBy(1 / 1.2);
$('screenshot').onclick = screenshot;
$('retry').onclick = () => { clearError(); if (!catalog.length || !viewer) init(); else loadSelection(); };
$('dismiss-error').onclick = clearError;
for (const button of document.querySelectorAll('[data-view]')) button.onclick = () => {
  viewer?.setView(button.dataset.view);
  for (const other of document.querySelectorAll('[data-view]')) { other.classList.toggle('active', other === button); other.setAttribute('aria-pressed', String(other === button)); }
};
for (const id of ['display-mode', 'scale-mode', 'color-mode', 'show-edges', 'show-labels', 'show-grid']) $(id).onchange = updateOptions;
document.addEventListener('keydown', event => {
  if (['INPUT', 'TEXTAREA', 'SELECT', 'BUTTON'].includes(event.target.tagName)) return;
  if (event.key.toLowerCase() === 'f') { event.preventDefault(); viewer?.fit(); }
});

function ensureViewer() {
  if (!viewer) viewer = new MeshViewer($('scene'), {onLabels: renderLabels, onError: message => message ? showError(String(message), true) : clearError()});
  viewer.setOptions(options);
}
function folderReady(fileList) {
  if (!fileList.length) return;
  ++generation; controller?.abort(); cache.clear();
  localFiles = new Map(); catalog = []; catalogById = new Map(); page = 0;
  $('search').value = '';
  $('total-count').textContent = '0 栋模型';
  $('source-path').textContent = '尚未选择可用的 OBJ 目录';
  $('folder-status').textContent = '请选择包含 OBJ 文件的目录';
  selectIds([]);
  const files = [...fileList].filter(file => /\.obj$/i.test(file.name));
  if (!files.length) { showError('这个文件夹中没有 OBJ 文件，请选择包含 .obj 模型的目录。'); return; }
  const mapped = new Map();
  for (const file of files) {
    const id = file.name.replace(/\.obj$/i, '');
    if (mapped.has(id)) { showError(`文件夹包含同名模型 ${file.name}，请直接选择只含一套结果的子文件夹。`); return; }
    mapped.set(id, file);
  }
  try { ensureViewer(); } catch (error) { showError(error.message); return; }
  ++generation; controller?.abort(); cache.clear();
  localFiles = mapped;
  catalog = [...mapped].map(([id, file]) => ({id, bytes: file.size})).sort((a, b) => a.id.localeCompare(b.id, undefined, {numeric: true}));
  catalogById = new Map(catalog.map(model => [model.id, model]));
  page = 0; $('search').value = '';
  const name = files[0].webkitRelativePath.split('/')[0] || '本地文件夹';
  $('source-path').textContent = name + '（浏览器选择的本地文件夹）';
  $('folder-status').textContent = `${number(files.length)} 个 OBJ · 仅按需读取所选楼栋`;
  $('total-count').textContent = `${number(files.length)} 栋模型`;
  selectIds([]);
}
$('choose-folder').onclick = () => $('folder-input').click();
$('folder-input').onchange = event => { folderReady(event.target.files); event.target.value = ''; };

function init() {
  try {
    ensureViewer();
    $('total-count').textContent = '尚未选择文件夹';
    $('source-path').textContent = '尚未选择文件夹。关闭或刷新网页后，请手动重新选择。';
    $('folder-status').textContent = '选择含 OBJ 的目录 · 文件仅在本机读取';
    selectIds([]);
  } catch (error) {
    $('scene-stats').textContent = '查看器暂时无法启动';
    $('loading').hidden = true;
    showError(`查看器启动失败：${error.message}。请使用支持 WebGL 的浏览器。`, true);
    $('empty-state').hidden = false;
  }
}
init();

})();
