import test from 'node:test';import assert from 'node:assert/strict';
import {NativeProjectFile,snapshotProjectTree,restoreProjectTree,nativeExportWriter} from '../src/shared/mobile-project.js';
import {readPointCloud} from '../src/cloud/point-io.js';
const bytes=new TextEncoder().encode('1 2 3 42\n4 5 6 99\n');let reads=[],exported=[];
globalThis.Capacitor={isNativePlatform:()=>true,registerPlugin:()=>({readChunk:async({offset,length})=>{reads.push(length);return{data:Buffer.from(bytes.subarray(offset,offset+length)).toString('base64')};},beginExport:async()=>({token:'t'}),appendExport:async({data})=>exported.push(Buffer.from(data,'base64')),cancelExport:async()=>{},finishExport:async()=>{},commitExport:async()=>({key:'stored'})})};
test('native disk file feeds real XYZI point reader and supports bounded slices',async()=>{const file=new NativeProjectFile('p',{path:'group/a.txt',size:bytes.length,key:'k'});const cloud=await readPointCloud(file,{maxPoints:0});assert.equal(cloud.count,2);assert.deepEqual(Array.from(cloud.positions).slice(0,3),[1,2,3]);assert.ok(reads.every(n=>n<=1048576));assert.equal(new TextDecoder().decode(await file.slice(-3).arrayBuffer()),'99\n');});
test('tree state roundtrip preserves tags, colors, removals and newly imported files',()=>{const project={groups:new Map([['g',{id:'g',name:'folder',parent:''}]]),serial:1,assign(e){e.group='';}};const entries=[{id:'a',group:'g',columnSettings:{tags:{a:'nx'}},displayColor:'#ff0000'}];const saved={...snapshotProjectTree(project,entries),knownIds:['a','removed']};project.groups.clear();const restored=restoreProjectTree(project,[{id:'a'},{id:'removed'},{id:'new'}],saved);assert.deepEqual(restored.map(e=>e.id),['a','new']);assert.equal(restored[0].displayColor,'#ff0000');assert.equal(restored[0].columnSettings.tags.a,'nx');assert.equal(project.groups.get('g').name,'folder');});
test('rejects folder cycles rather than hanging on restored projects',()=>assert.throws(()=>restoreProjectTree({groups:new Map()},[],{groups:[{id:'a',parent:'b'},{id:'b',parent:'a'}],items:[]}),/cycle/));
test('native writer chunks binary data without whole-output base64 copies',async()=>{exported=[];const writer=await nativeExportWriter('cloud.ply');const input=new Uint8Array(600000).fill(201);await writer.write(input);assert.equal(exported.length,3);assert.ok(exported.every(b=>b.length<=262144));assert.deepEqual(Buffer.concat(exported),Buffer.from(input));assert.equal((await writer.commit('p','cloud.ply')).key,'stored');});

test('autosave retains a quick revert while a prior write is in flight',async()=>{
 const {createMobileSaver}=await import('../src/shared/mobile-project.js');let value='A',release,written=[];
 const saver=createMobileSaver({read:()=>({value}),write:async state=>{written.push(state.value);if(state.value==='B')await new Promise(r=>release=r);}});
 await saver.flush();value='B';const saving=saver.flush();value='A';saver.flush();release();await saving;assert.deepEqual(written,['A','B','A']);
});
test('an unchanged autosave does not block subsequent edits',async()=>{const {createMobileSaver}=await import('../src/shared/mobile-project.js');let value=1;const values=[];const saver=createMobileSaver({read:()=>({value}),write:async state=>values.push(state.value)});await saver.flush();await saver.flush();value=2;await saver.flush();assert.deepEqual(values,[1,2]);});
