import assert from 'node:assert/strict';
import { ViewerProject } from '../src/shared/project-model.js';
import {appendLodFiles,appendWireFiles} from '../src/shared/project-import.js';
const file = (path,size=20) => ({name:path.split('/').at(-1),webkitRelativePath:path,size,lastModified:1});
const project = new ViewerProject(), models = [], first = file('a/101.obj');
assert.deepEqual(appendLodFiles(models,project,[first]),{added:1,duplicates:0});
const entry = models[0], other = file('b/101.obj');
assert.deepEqual(appendLodFiles(models,project,[file('a/101.obj'),other]),{added:1,duplicates:1});
assert.equal(models[0],entry);assert.equal(entry.file,first);assert.equal(models[1].id,'101_2');
assert.equal(project.path(models[1].group),'b');assert.notEqual(entry.key,models[1].key);
const review=project.create('Review');project.move(entry,review);
assert.equal(appendLodFiles(models,project,[first]).duplicates,1);assert.equal(entry.group,review);
console.log('PASS LOD appends imports, preserves cache identity, handles duplicate IDs, and deduplicates after moves');
const sets=[], wireProject=new ViewerProject();
const files=[file('dataset/101/a.obj'),file('dataset/101/pc.xyz'),file('dataset/102/b.obj')];
assert.deepEqual(appendWireFiles(sets,wireProject,files),{added:3,duplicates:0});
assert.equal(sets.length,2);assert.equal(sets[0].treeName,'101');assert.equal(wireProject.path(sets[0].group),'dataset');
const set=sets[0], original=set.wires[0];
assert.deepEqual(appendWireFiles(sets,wireProject,[...files,file('dataset/101/z.obj')]),{added:1,duplicates:3});
assert.equal(sets[0],set);assert.equal(set.wires[0],original);assert.equal(set.wires.length,2);
wireProject.move(set,'');appendWireFiles(sets,wireProject,[file('dataset/101/c.obj')]);
assert.equal(set.group,'');assert.equal(set.wires[2].name,'c.obj');
appendWireFiles(sets,wireProject,[file('other/101/a.obj')]);assert.equal(sets.length,3);assert.notEqual(sets[2].id,set.id);
const loose=[], looseProject=new ViewerProject();appendWireFiles(loose,looseProject,[file('a.obj'),file('pc.txt')]);
assert.equal(loose.length,1);assert.equal(loose[0].clouds.length,1);
console.log('PASS wire sets append in stable order, retain virtual moves, and isolate same IDs in different datasets');
