package io.github.sen2maker.buildingwebviewer.preview;
import android.app.AlertDialog;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import androidx.core.content.FileProvider;
import com.getcapacitor.*;
import org.json.JSONObject;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
/** Native diagnostics remain reachable when the web page or its JavaScript cannot start. */
final class StartupDiagnostics {
  final MainActivity activity;final ArrayDeque<String> events=new ArrayDeque<>();final File log;
  String previous="",lastFailure="",probe="not yet available";Bridge bridge;Button access;AlertDialog activeDialog;boolean showing=false,rendererGone=false;
  StartupDiagnostics(MainActivity activity){this.activity=activity;log=new File(activity.getFilesDir(),"startup-diagnostics.txt");try(InputStream in=new FileInputStream(log)){previous=ProjectStore.readText(in);}catch(Exception ignored){}record("START","Local startup; optional updates never gate loading");}
  synchronized void record(String type,String detail){events.addLast(new Date()+" "+type+" "+DiagnosticText.message(detail));while(events.size()>60)events.removeFirst();try(FileOutputStream out=new FileOutputStream(log)){out.write(String.join("\n",events).getBytes(StandardCharsets.UTF_8));}catch(Exception ignored){}}
  void install(Bridge bridge){this.bridge=bridge;record("ENTRY",DiagnosticText.url(bridge.getLocalUrl()+bridge.getConfig().getStartPath()));
    bridge.setWebViewClient(new BridgeWebViewClient(bridge){
      @Override public void onPageStarted(WebView view,String url,android.graphics.Bitmap icon){activity.backNavigation.update(url);record("NAVIGATE",DiagnosticText.url(url));super.onPageStarted(view,url,icon);}
      @Override public void onPageFinished(WebView view,String url){super.onPageFinished(view,url);record("LOADED",DiagnosticText.url(url));
        if(url.equals(bridge.getErrorUrl())){if(lastFailure.isEmpty())lastFailure=bridge.isMinimumWebViewInstalled()?"Fallback page reached; inspect events for actual failure":"WebView below configured minimum";showAccess();}
        view.evaluateJavascript("JSON.stringify({ready:document.readyState,native:!!(window.Capacitor&&window.Capacitor.isNativePlatform&&window.Capacitor.isNativePlatform()),home:!!document.getElementById('projects'),projectsRendered:!!(document.getElementById('projects')&&document.getElementById('projects').children.length)})",value->{probe=value;record("PAGE_STATE",value);});
      }
      @Override public void onReceivedError(WebView view,WebResourceRequest request,WebResourceError error){record("WEB_ERROR",(request.isForMainFrame()?"main":"resource")+" code="+error.getErrorCode()+" "+error.getDescription()+" "+DiagnosticText.url(request.getUrl().toString()));if(request.isForMainFrame())failure("页面加载失败 / Page load failed: "+error.getErrorCode()+" "+error.getDescription());super.onReceivedError(view,request,error);}
      @Override public void onReceivedHttpError(WebView view,WebResourceRequest request,WebResourceResponse response){record("HTTP_ERROR",(request.isForMainFrame()?"main":"resource")+" status="+response.getStatusCode()+" "+DiagnosticText.url(request.getUrl().toString()));if(request.isForMainFrame())failure("页面响应错误 / Page response: HTTP "+response.getStatusCode());super.onReceivedHttpError(view,request,response);}
      @Override public void onReceivedSslError(WebView view,SslErrorHandler handler,android.net.http.SslError error){record("TLS_ERROR","code="+error.getPrimaryError()+" "+DiagnosticText.url(error.getUrl()));handler.cancel();failure("连接证书校验失败 / TLS verification failed");}
      @Override public boolean onRenderProcessGone(WebView view,RenderProcessGoneDetail detail){rendererGone=true;record("RENDERER_EXIT","crashed="+detail.didCrash());if(view.getParent() instanceof ViewGroup)((ViewGroup)view.getParent()).removeView(view);view.destroy();failure("渲染进程退出，请关闭并重开 App / Renderer exited; reopen app");return true;}
    });
    bridge.getWebView().setWebChromeClient(new BridgeWebChromeClient(bridge){@Override public boolean onConsoleMessage(ConsoleMessage message){if(message.messageLevel()==ConsoleMessage.MessageLevel.ERROR){record("JS_ERROR",DiagnosticText.url(message.sourceId())+":"+message.lineNumber()+" "+message.message());showAccess();}return super.onConsoleMessage(message);}});
    activity.getWindow().getDecorView().postDelayed(()->{if(!activity.isFinishing()&&!rendererGone&&probe.equals("not yet available")){record("BOOT_TIMEOUT","No page completion after 12 seconds");showAccess();}},12000);
  }
  void failure(String reason){lastFailure=DiagnosticText.message(reason);activity.runOnUiThread(()->{showAccess();if(!showing)show();});}
  void showAccess(){activity.runOnUiThread(()->{if(activity.isFinishing()||activity.isDestroyed()||access!=null)return;FrameLayout root=activity.findViewById(android.R.id.content);access=new Button(activity);access.setText("诊断 / Diagnose");access.setTextSize(11);access.setOnClickListener(v->show());FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM|Gravity.END);p.bottomMargin=48;p.rightMargin=12;root.addView(access,p);});}
  String report(){StringBuilder text=new StringBuilder("BuildingWebViewer startup report\n");try{android.content.pm.PackageInfo app=activity.getPackageManager().getPackageInfo(activity.getPackageName(),0);text.append("APK: ").append(app.versionName).append(" (").append(app.versionCode).append(")\n");}catch(Exception ignored){}
    text.append("Device: ").append(Build.MANUFACTURER).append(' ').append(Build.MODEL).append("\nAndroid: ").append(Build.VERSION.RELEASE).append(" / API ").append(Build.VERSION.SDK_INT).append('\n');
    if(Build.VERSION.SDK_INT>=26){android.content.pm.PackageInfo engine=WebView.getCurrentWebViewPackage();if(engine!=null)text.append("WebView package: ").append(engine.packageName).append(' ').append(engine.versionName).append('\n');}
    if(bridge!=null){text.append("Expected entry: ").append(DiagnosticText.url(bridge.getLocalUrl()+bridge.getConfig().getStartPath())).append("\nMinimum WebView: ").append(bridge.getConfig().getMinWebViewVersion()).append('\n');if(!rendererGone)text.append("Actual URL: ").append(DiagnosticText.url(bridge.getWebView().getUrl())).append("\nUA: ").append(bridge.getWebView().getSettings().getUserAgentString()).append('\n');try{text.append("Local web version: ").append(new WebUpdater(activity).currentVersion(bridge.getServerBasePath())).append('\n');}catch(Exception e){text.append("Local version unreadable\n");}}
    for(String asset:new String[]{"assets/mobile/index.html","assets/js/compatibility.js","assets/js/capacitor.js","assets/js/mobile.bundle.js"})try(InputStream in=activity.getAssets().open("public/"+asset)){text.append("Bundled asset OK: ").append(asset).append('\n');}catch(Exception e){text.append("Bundled asset MISSING: ").append(asset).append('\n');}
    text.append("Last failure: ").append(lastFailure.isEmpty()?"none recorded":lastFailure).append("\nPage state: ").append(probe).append("\n\nThis launch:\n");synchronized(this){for(String event:events)text.append(event).append('\n');}if(!previous.isEmpty())text.append("\nPrevious launch:\n").append(previous);return text.toString();
  }
  void show(){activity.runOnUiThread(()->{if(activity.isFinishing()||activity.isDestroyed()||showing)return;showing=true;String report=report();LinearLayout box=new LinearLayout(activity);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(24,8,24,8);TextView note=new TextView(activity);note.setText("报告保存在本机，不自动上传，不读取点云内容。包含设备、错误和加载地址。\nLocal report only; share it manually if needed.");box.addView(note);Button retry=new Button(activity);retry.setText("重试本地首页 / Retry local home");retry.setEnabled(!rendererGone&&bridge!=null);box.addView(retry);Button bundled=new Button(activity);bundled.setText("使用内置页面（保留项目） / Use bundled pages");bundled.setEnabled(!rendererGone&&bridge!=null);box.addView(bundled);TextView content=new TextView(activity);content.setText(report);content.setTextIsSelectable(true);content.setTextSize(11);ScrollView scroll=new ScrollView(activity);scroll.addView(content);box.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
      AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("启动诊断 / Startup diagnostics").setView(box).create();
      LinearLayout actions=new LinearLayout(activity);String[] labels={"复制\nCopy","导出\nExport","关闭\nClose"};for(int i=0;i<labels.length;i++){final int action=i;Button button=new Button(activity);button.setText(labels[i]);button.setAllCaps(false);button.setTextSize(11);button.setMinWidth(0);button.setMinimumWidth(0);actions.addView(button,new LinearLayout.LayoutParams(0,-2,1));button.setOnClickListener(v->{if(action==0){android.content.ClipboardManager clipboard=(android.content.ClipboardManager)activity.getSystemService(Context.CLIPBOARD_SERVICE);clipboard.setPrimaryClip(ClipData.newPlainText("BuildingWebViewer diagnostics",report));Toast.makeText(activity,"已复制 / Copied",Toast.LENGTH_SHORT).show();}else{dialog.dismiss();if(action==1)export(report);}});}box.addView(actions);
      activeDialog=dialog;dialog.setOnDismissListener(d->{showing=false;activeDialog=null;});retry.setOnClickListener(v->{dialog.dismiss();lastFailure="";bridge.getWebView().loadUrl(bridge.getLocalUrl()+bridge.getConfig().getStartPath());});bundled.setOnClickListener(v->{dialog.dismiss();new WebUpdater(activity).prefs.edit().remove("active").remove("previous").putBoolean("booting",false).commit();record("RECOVERY","User selected bundled pages; project storage untouched");bridge.setServerAssetPath("public");});dialog.show();if(dialog.getWindow()!=null)dialog.getWindow().setLayout(-1,(int)(activity.getResources().getDisplayMetrics().heightPixels*0.85));
    });}
  void healthy(){if(rendererGone)return;probe="Native project list ready";lastFailure="";record("HOME_READY",probe);if(access!=null){if(access.getParent() instanceof ViewGroup)((ViewGroup)access.getParent()).removeView(access);access=null;}}
  void dispose(){if(activeDialog!=null)activeDialog.dismiss();}
  void export(String report){try{File dir=new File(activity.getCacheDir(),"exports/diagnostics");dir.mkdirs();File file=new File(dir,"BuildingWebViewer-diagnostics.txt");try(FileOutputStream out=new FileOutputStream(file)){out.write(report.getBytes(StandardCharsets.UTF_8));}Uri uri=FileProvider.getUriForFile(activity,activity.getPackageName()+".fileprovider",file);Intent share=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);share.setClipData(ClipData.newRawUri("diagnostics",uri));activity.startActivity(Intent.createChooser(share,"导出诊断 / Export diagnostics"));}catch(Exception e){Toast.makeText(activity,e.getMessage(),Toast.LENGTH_LONG).show();}}
}
